openapi: 3.0.1
info:
  title: WIEDPUG API
  description: API Documentation for the WIEDPUG Network
  termsOfService: https://wiedpug.github.io/wiedpug
  contact:
    name: WIEDPUG Team
    url: https://wiedpug.github.io/wiedpug
    email: changethis@email.com
  license:
    name: Applicable License
    url: https://wiedpug.github.io/wiedpug
  version: v0.0
paths:
  /v0/organisation-details/data:
    post:
      tags:
        - Organisation Details
      summary: Retrieves the organisationdetails
      operationId: GetOrganisationDetails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetOrganisationDetailsRequest'
            example:
              countryOfOrigin: AU
              documentOriginator:
                organizationCode: ABCD
              softwareIdentifier:
                softwareCompany: 1
                version: 1082
                programName: NETR
              abn: '72001967184'
              startDateTimeStatusRequest: '2024-02-01T19:25:04Z'
              endDateTimeStatusRequest: '2024-03-21T19:25:04Z'
              useNetworkDateTime: true
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganisationDetailsApiResult'
              example:
                isSuccessful: true
                data:
                  transmissionHeader:
                    dateFormatLastRevised: '2020-07-15'
                    dateTransmissionFileCreated: '2016-01-17'
                    countryOfOrigin: AU
                    documentOriginator:
                      organizationCode: ABCD
                    versionNumber: 31
                    softwareIdentifier:
                      softwareCompany: 6
                      version: 1082
                      programName: NETR
                    abn: '72001925678'
                  organisationDetailCollection:
                    - id: '1'
                      organisation:
                        organizationCode: AWTS
                      nameOfOrganisation: AWTA - EDI TESTING BY EXTERNAL CLIENTS
                      dateLastUpdated: '2020-04-28'
                      industryGroupId: E
                      transmitterFlag: 'Y'
                      phoneNumber:
                        standardPhoneNumber:
                          countryCode: '61'
                          number: '0317229370'
                      faxNumber:
                        standardPhoneNumber:
                          countryCode: '61'
                          number: '03763262290'
                      addresses:
                        - street: 88 HARBOR ROAD
                          suburb: KENSINGTON
                          postCode: '3031'
                          country: AU
                      contacts:
                        - firstName: HEAD OFFICE
                          phoneNumber:
                            standardPhoneNumber:
                              countryCode: '61'
                              number: '0309332782'
                    - id: '2'
                      organisation:
                        organizationCode: ABCD
                      nameOfOrganisation: DEMO BUYER 1
                      dateLastUpdated: '2020-04-28'
                      industryGroupId: E
                      transmitterFlag: 'N'
                    - id: '3'
                      organisation:
                        organizationCode: AWTN
                      nameOfOrganisation: AUSTRALIAN WOOL TESTING AUTH LTD
                      dateLastUpdated: '2020-04-28'
                      industryGroupId: A
                      transmitterFlag: 'Y'
                      phoneNumber:
                        standardPhoneNumber:
                          countryCode: '61'
                          number: '0254009986'
                      addresses:
                        - street: 367 NEW HAMMER STREET
                          suburb: NEWCASTLE
                          postCode: '2031'
                          country: AU
                      contacts:
                        - firstName: MIKE
                          lastName: PWOELL
                          phoneNumber:
                            standardPhoneNumber:
                              countryCode: '61'
                              number: '0387569072'
                          mobileNumber:
                            standardPhoneNumber:
                              countryCode: '61'
                              number: '0353298764'
                          email: mpowell@awtn.co.au
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred
                status: 400
                detail: ''
                errors:
                  Requests[0].TransmissionHeader.DateFormatLastRevised:
                    - The field DateFormatLastRevised is required
                    - The field DateFormatLastRevised must match regulart expression pattern...
                  Requests[0].TransmissionHeader.CountryOfOrigin:
                    - The field CountryOfOrigin is required
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: Resource not found
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
  /v0/organisation-details/{id}:
    get:
      tags:
        - Organisation Details
      summary: Retrieves the organisationdetail by id
      operationId: GetOrganisationDetailsById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganisationDetailApiResult'
              example:
                transmissionHeader:
                  dateFormatLastRevised: '2020-07-15'
                  dateTransmissionFileCreated: '2016-01-17'
                  countryOfOrigin: AU
                  documentOriginator:
                    organizationCode: ABCD
                  abn: '43006014106'
                organisationDetailCollection:
                  - id: '1'
                    organisation:
                      organizationCode: ABCD
                    nameOfOrganisation: AWTA - EDI TESTING BY EXTERNAL CLIENTS
                    dateLastUpdated: '2020-04-28'
                    industryGroupId: T
                    transmitterFlag: 'Y'
                    phoneNumber:
                      standardPhoneNumber:
                        countryCode: '61'
                        number: '0389004637'
                    faxNumber:
                      standardPhoneNumber:
                        countryCode: '61'
                        number: '0320874405'
                    addresses:
                      - street: 28 GREAT SOUTH ROAD
                        suburb: KENSINGTON
                        postCode: '3031'
                        country: AU
                    contacts:
                      - firstName: HEAD OFFICE
                        phoneNumber:
                          standardPhoneNumber:
                            countryCode: '61'
                            number: '0310108809'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: Resource not found
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
    put:
      tags:
        - Organisation Details
      summary: Update the organisation detail by id
      operationId: UpdateOrganisationDetailsById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganisationDetail'
            example:
              transmissionHeader:
                dateFormatLastRevised: '2020-07-15'
                dateTransmissionFileCreated: '2016-01-17'
                countryOfOrigin: AU
                documentOriginator:
                  organizationCode: ABCD
                abn: '43006014106'
              organisationDetailCollection:
                - organisation:
                    organizationCode: ABCD
                  nameOfOrganisation: AWTA - EDI TESTING BY EXTERNAL CLIENTS
                  dateLastUpdated: '2020-04-28'
                  industryGroupId: E
                  transmitterFlag: 'Y'
                  phoneNumber:
                    standardPhoneNumber:
                      countryCode: '61'
                      number: '0389004637'
                  faxNumber:
                    standardPhoneNumber:
                      countryCode: '61'
                      number: '0320874405'
                  addresses:
                    - street: 28 GREAT SOUTH ROAD
                      suburb: KENSINGTON
                      postCode: '3031'
                      country: AU
                  contacts:
                    - firstName: HEAD OFFICE
                      phoneNumber:
                        standardPhoneNumber:
                          countryCode: '61'
                          number: '0310108809'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResult'
              example:
                transmissionHeader:
                  dateFormatLastRevised: '2020-07-15'
                  dateTransmissionFileCreated: '2016-01-17'
                  countryOfOrigin: AU
                  documentOriginator:
                    organizationCode: ABCD
                  abn: '43006014106'
                organisationDetailCollection:
                  - id: '1'
                    organisation:
                      organizationCode: ABCD
                    nameOfOrganisation: AWTA - EDI TESTING BY EXTERNAL CLIENTS
                    dateLastUpdated: '2020-04-28'
                    industryGroupId: T
                    transmitterFlag: 'Y'
                    phoneNumber:
                      standardPhoneNumber:
                        countryCode: '61'
                        number: '0389004637'
                    faxNumber:
                      standardPhoneNumber:
                        countryCode: '61'
                        number: '0320874405'
                    addresses:
                      - street: 28 GREAT SOUTH ROAD
                        suburb: KENSINGTON
                        postCode: '3031'
                        country: AU
                    contacts:
                      - firstName: HEAD OFFICE
                        phoneNumber:
                          standardPhoneNumber:
                            countryCode: '61'
                            number: '0310108809'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred
                status: 400
                detail: ''
                errors:
                  Requests[0].TransmissionHeader.DateFormatLastRevised:
                    - The field DateFormatLastRevised is required
                    - The field DateFormatLastRevised must match regulart expression pattern...
                  Requests[0].TransmissionHeader.CountryOfOrigin:
                    - The field CountryOfOrigin is required
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: Resource not found
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
    delete:
      tags:
        - Organisation Details
      summary: Delete or Deactivate organisation detail by id
      operationId: DeleteOrganisationDetailsById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResult'
              example:
                isSuccessful: true
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: Resource not found
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
components:
  schemas:
    Address:
      type: object
      properties:
        firstName:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        lastName:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        organisationName:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        premise:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        street:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        suburb:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        city:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        regionOrState:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        postCode:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        country:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
      additionalProperties: false
    ApiResult:
      required:
        - isSuccessful
      type: object
      properties:
        isSuccessful:
          type: boolean
          description: Indicator if the request has been successfully processed.
        message:
          type: string
          description: Contains information about the response if applicable.
          nullable: true
        data:
          description: Contains response data. e.g. Auction Catalogue
          nullable: true
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    Centre:
      enum:
        - AU_A
        - AU_AD
        - AU_AR
        - AU_AU
        - AU_B
        - AU_BA
        - AU_BK
        - AU_BL
        - AU_BM
        - AU_BO
        - AU_BR
        - AU_BT
        - AU_C
        - AU_CA
        - AU_CB
        - AU_CC
        - AU_CL
        - AU_CN
        - AU_CO
        - AU_CR
        - AU_CU
        - AU_CW
        - AU_D
        - AU_DE
        - AU_DO
        - AU_DR
        - AU_E
        - AU_ER
        - AU_ES
        - AU_F
        - AU_G
        - AU_GF
        - AU_GI
        - AU_GN
        - AU_GR
        - AU_GU
        - AU_H
        - AU_HA
        - AU_HB
        - AU_HM
        - AU_HO
        - AU_HY
        - AU_I
        - AU_J
        - AU_JA
        - AU_K
        - AU_KE
        - AU_KH
        - AU_KI
        - AU_KN
        - AU_KT
        - AU_KW
        - AU_KY
        - AU_L
        - AU_LC
        - AU_M
        - AU_MA
        - AU_MB
        - AU_MC
        - AU_ME
        - AU_MG
        - AU_MI
        - AU_MO
        - AU_MR
        - AU_MU
        - AU_N
        - AU_NA
        - AU_ND
        - AU_NO
        - AU_NR
        - AU_OB
        - AU_OR
        - AU_P
        - AU_PA
        - AU_PL
        - AU_Q
        - AU_QU
        - AU_R
        - AU_S
        - AU_SG
        - AU_SH
        - AU_SK
        - AU_SW
        - AU_SY
        - AU_T
        - AU_TE
        - AU_U
        - AU_UR
        - AU_V
        - AU_W
        - AU_WA
        - AU_WG
        - AU_WL
        - AU_WN
        - AU_WR
        - AU_WW
        - AU_X
        - AU_Y
        - AU_YA
        - AU_YM
        - AU_YO
        - AU_Z
        - OS_ZA
        - OS_ZB
        - OS_ZC
        - OS_ZD
        - OS_ZE
        - OS_ZF
        - OS_ZG
        - OS_ZH
        - OS_ZI
        - OS_ZJ
        - OS_ZK
        - OS_ZL
        - OS_ZM
        - OS_ZN
        - OS_ZO
        - OS_ZP
        - OS_ZQ
        - OS_ZR
        - OS_ZS
        - OS_ZT
        - OS_ZU
        - OS_ZV
        - OS_ZW
        - OS_ZX
        - OS_ZY
        - OS_ZZ
        - NZ_A
        - NZ_AW
        - NZ_B
        - NZ_BL
        - NZ_BT
        - NZ_C
        - NZ_CV
        - NZ_D
        - NZ_F
        - NZ_FA
        - NZ_G
        - NZ_GD
        - NZ_GO
        - NZ_HA
        - NZ_HS
        - NZ_I
        - NZ_J
        - NZ_K
        - NZ_KA
        - NZ_KP
        - NZ_L
        - NZ_LO
        - NZ_LU
        - NZ_M
        - NZ_MA
        - NZ_MK
        - NZ_MT
        - NZ_MU
        - NZ_N
        - NZ_NE
        - NZ_O
        - NZ_OH
        - NZ_OI
        - NZ_OM
        - NZ_OT
        - NZ_P
        - NZ_PT
        - NZ_PU
        - NZ_R
        - NZ_RG
        - NZ_RI
        - NZ_S
        - NZ_SA
        - NZ_SH
        - NZ_SY
        - NZ_T
        - NZ_TA
        - NZ_TE
        - NZ_TH
        - NZ_TP
        - NZ_U
        - NZ_V
        - NZ_W
        - NZ_WH
        - NZ_WI
        - NZ_WR
        - NZ_WT
        - NZ_WU
        - NZ_X
        - NZ_Y
        - NZ_YP
        - NZ_Z
      type: string
      description: ''
    Contact:
      type: object
      properties:
        description:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        firstName:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        lastName:
          maxLength: 80
          minLength: 0
          type: string
          nullable: true
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        mobileNumber:
          $ref: '#/components/schemas/PhoneNumber'
        email:
          maxLength: 80
          minLength: 0
          type: string
          format: email
          nullable: true
      additionalProperties: false
    CountryCode:
      enum:
        - AU
        - NZ
        - FR
        - ZA
      type: string
      description: 'A code for the country in which the transmission was created. Country Code using ISO 3166-1 standard<br />AU: Australia<br />NZ: New Zealand<br />FR: France<br />ZA: South Africa'
    CustomProblemDetails:
      required:
        - status
        - title
      type: object
      properties:
        type:
          type: string
          description: "A URI reference [RFC3986] that identifies the problem type.\r\nThis specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]). \r\nWhen this member is not present, its value is assumed to be \"about:blank\".      \r\ne.g. For 400 Bad Request, the \"type\" value can be \"https://tools.ietf.org/html/rfc9110#section-15.5.1\""
          nullable: true
        title:
          minLength: 1
          type: string
          description: "A short, human-readable summary of the problem type. \r\nIt SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4).\r\ne.g. \"One or more validation errors occurred.\""
        status:
          type: integer
          description: The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
          format: int32
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem. e.g. 400, 403, etc.
          nullable: true
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
            nullable: true
          description: 'Dictionary of errors in <PropertyName, ErrorDetails[]> format. e.g. errors: { "name": ["Product name is required"], "category": ["Category name cannot be longer than 20 characters."]  }'
          nullable: true
      additionalProperties: false
      description: A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.
    GetOrganisationDetailsRequest:
      required:
        - abn
        - countryOfOrigin
        - documentOriginator
      type: object
      properties:
        countryOfOrigin:
          $ref: '#/components/schemas/CountryCode'
        documentOriginator:
          $ref: '#/components/schemas/Organisation'
        softwareIdentifier:
          $ref: '#/components/schemas/SoftwareIdentifier'
        abn:
          maxLength: 11
          minLength: 0
          type: string
          description: Australian Business Number
        startDateTimeStatusRequest:
          maxLength: 20
          minLength: 0
          pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
          type: string
          description: 'Date and Time in UTC format in ISO 8601 standard. Format: YYYY-MM-DDTHH:mm:ssZ e.g. 2024-03-21T19:25:04Z'
          format: date-time
          nullable: true
        endDateTimeStatusRequest:
          maxLength: 20
          minLength: 0
          pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
          type: string
          description: 'Date and Time in UTC format in ISO 8601 standard. Format: YYYY-MM-DDTHH:mm:ssZ. e.g. 2024-03-21T19:25:04Z'
          format: date-time
          nullable: true
        useNetworkDateTime:
          maxLength: 5
          minLength: 0
          type: boolean
          nullable: true
      additionalProperties: false
    IndustryGroupId:
      enum:
        - A
        - C
        - E
        - D
        - M
        - P
        - S
        - T
        - V
      type: string
      description: 'A: Agent / Broker<br />C: Carrier<br />E: Exporter / Buyer<br />D: Dump<br />M: Miscellaneous<br />P: Port<br />S: Shipping<br />T: Test House<br />V: Vessel'
    Organisation:
      type: object
      properties:
        organizationAndCentre:
          $ref: '#/components/schemas/OrganisationAndCentre'
        organizationCode:
          maxLength: 5
          minLength: 0
          type: string
          nullable: true
      additionalProperties: false
    OrganisationAndCentre:
      required:
        - centre
        - organizationCode
      type: object
      properties:
        organizationCode:
          maxLength: 3
          minLength: 0
          type: string
        centre:
          $ref: '#/components/schemas/Centre'
      additionalProperties: false
    OrganisationDetail:
      required:
        - dateLastUpdated
        - industryGroupId
        - nameOfOrganisation
        - organisation
        - transmitterFlag
      type: object
      properties:
        id:
          type: string
          nullable: true
        organisation:
          $ref: '#/components/schemas/Organisation'
        nameOfOrganisation:
          maxLength: 50
          minLength: 0
          type: string
        dateLastUpdated:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD)
          format: date
        industryGroupId:
          $ref: '#/components/schemas/IndustryGroupId'
        transmitterFlag:
          maxLength: 1
          minLength: 0
          type: string
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        abn:
          maxLength: 11
          minLength: 0
          pattern: ^[0-9]+$
          type: string
          description: Australian Business Number
          nullable: true
        faxNumber:
          $ref: '#/components/schemas/PhoneNumber'
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
          nullable: true
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
          nullable: true
      additionalProperties: false
    OrganisationDetailApiResult:
      required:
        - isSuccessful
      type: object
      properties:
        isSuccessful:
          type: boolean
          description: Indicator if the request has been successfully processed.
        message:
          type: string
          description: Contains information about the response if applicable.
          nullable: true
        data:
          $ref: '#/components/schemas/OrganisationDetail'
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    OrganisationDetails:
      required:
        - organisationDetailCollection
        - transmissionHeader
      type: object
      properties:
        transmissionHeader:
          $ref: '#/components/schemas/TransmissionHeader'
        organisationDetailCollection:
          type: array
          items:
            $ref: '#/components/schemas/OrganisationDetail'
      additionalProperties: false
    OrganisationDetailsApiResult:
      required:
        - isSuccessful
      type: object
      properties:
        isSuccessful:
          type: boolean
          description: Indicator if the request has been successfully processed.
        message:
          type: string
          description: Contains information about the response if applicable.
          nullable: true
        data:
          $ref: '#/components/schemas/OrganisationDetails'
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    PhoneNumber:
      required:
        - standardPhoneNumber
      type: object
      properties:
        standardPhoneNumber:
          $ref: '#/components/schemas/StandardPhoneNumber'
        extension:
          maxLength: 15
          minLength: 0
          type: string
          description: Used for landline or fax extentions
          nullable: true
      additionalProperties: false
    SoftwareCompany:
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
      type: integer
      description: '1: Talman<br />2: Symbotic<br />3: Jumbuck/Datacon<br />4: Jemalong<br />5: NA - no value<br />6: Modiano<br />7: AWH<br />6: AWTA'
      format: int32
    SoftwareIdentifier:
      type: object
      properties:
        softwareCompany:
          $ref: '#/components/schemas/SoftwareCompany'
        version:
          pattern: '-?\d{1,4}'
          type: integer
          description: Version no. e.g. 2400
          format: int32
          nullable: true
        programName:
          maxLength: 4
          minLength: 0
          type: string
          nullable: true
      additionalProperties: false
    StandardPhoneNumber:
      required:
        - countryCode
        - number
      type: object
      properties:
        countryCode:
          maxLength: 3
          minLength: 0
          pattern: ^[0-9]+$
          type: string
        number:
          maxLength: 15
          minLength: 0
          pattern: ^[0-9]+$
          type: string
      additionalProperties: false
    TransmissionHeader:
      required:
        - abn
        - countryOfOrigin
        - dateFormatLastRevised
        - dateTransmissionFileCreated
        - documentOriginator
      type: object
      properties:
        dateFormatLastRevised:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD)
          format: date
        dateTransmissionFileCreated:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD)
          format: date
        countryOfOrigin:
          $ref: '#/components/schemas/CountryCode'
        documentOriginator:
          $ref: '#/components/schemas/Organisation'
        versionNumber:
          pattern: '-?\d{1,2}'
          type: integer
          description: Two digits. e.g. 99
          format: int32
          nullable: true
        softwareIdentifier:
          $ref: '#/components/schemas/SoftwareIdentifier'
        abn:
          maxLength: 11
          minLength: 0
          pattern: ^[0-9]+$
          type: string
          description: Australian Business Number, 11 digits string
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Access Token that is added in the Authorization header of the HTTP request. Example: "Authorization: Bearer {token}". The JWT serves as a credential that proves the identity of the client to the server.'
      name: Authorization
      in: header
    oauth2:
      type: oauth2
      description: Authentication for client applications by providing Client ID and Client Secret for an JWT Access Token.
      flows:
        clientCredentials:
          tokenUrl: /auth-server/oauth/token
          scopes: {}
security:
  - Bearer: []
