openapi: 3.0.1
info:
  title: WIEDPUG API
  description: API Documentation for the WIEDPUG Network
  termsOfService: https://wiedpug.github.io/wiedpug
  contact:
    name: WIEDPUG Team
    url: https://wiedpug.github.io/wiedpug
    email: changethis@email.com
  license:
    name: Applicable License
    url: https://wiedpug.github.io/wiedpug
  version: v0.0
paths:
  /v0/dark-and-medullated-fibre-risk-verification:
    post:
      tags:
        - Dark And Medullated Fibre Risk Verification
      summary: Dark And Medullated Fibre Risk Verification
      description: Sent by a broker organisation to AWTA to include the Dark and Medullated Fibre Risk (DMFR) on a Certificate that has been issued.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DarkAndMedullatedFibreRiskVerification'
            example:
              transmissionHeader:
                dateFormatLastRevised: '2020-07-15'
                dateTransmissionFileCreated: '2016-01-17'
                countryOfOrigin: AU
                documentOriginator:
                  organisationCode: ABC
                currentReceiver:
                  organisationCode: ATW
                versionNumber: 31
                softwareIdentifier:
                  softwareCompany: 8
                  version: 1082
                  programName: NETR
                abn: '72001967184'
              darkAndMedullatedFibreRiskDetailsCollection:
                - declaredBreed: A
                  declaredWoolSubCategory: W
                  declaredWoolCategory: P
                  declaredQualifierCodes:
                    - A
                    - H
                    - D
                    - H
                    - S
                    - T
                  declaredQualifierScale: 1
                  isContactingWithExoticBreeds: true
                  isCrutched: true
                  isCrutchedWithin3MonthsOfShearing: false
                  sex: E
                  ageFrom: 12
                  ageTo: 23
                  darkAndMedullatedFibreRiskBroker: 1
                  darkandMedullatedFibreRisk: D
                  certificateIdentity:
                    certificateIDPrefix: 3
                    certificateIDNumber: 499
                    certificateIDSuffix: P
                    certificateIDCD: 7
                  woolBase: 32.14
                  dmfrErrorFields:
                    - '12'
                    - '18'
                    - '9'
                    - '2'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResult'
              example: {}
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiErrorResult'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred
                status: 400
                detail: ''
                errors:
                  errors:
                    Requests[0].TransmissionHeader.DateFormatLastRevised:
                      - The field DateFormatLastRevised is required
                      - The field DateFormatLastRevised must match regulart expression pattern...
                    Requests[0].TransmissionHeader.CountryOfOrigin:
                      - The field CountryOfOrigin is required
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiErrorResult'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiErrorResult'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiErrorResult'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
  /v0/dark-and-medullated-fibre-risk-verification/data:
    post:
      tags:
        - Dark And Medullated Fibre Risk Verification
      summary: Retrieves the dark and medullated fibre risk verification
      operationId: RequestForDarkAndMedullatedFibreRiskVerification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestForData'
            example:
              transmissionHeader:
                dateFormatLastRevised: '2020-07-15'
                dateTransmissionFileCreated: '2016-01-17'
                countryOfOrigin: AU
                documentOriginator:
                  organisationCode: ABC
                currentReceiver:
                  organisationCode: ATW
                versionNumber: 31
                softwareIdentifier:
                  softwareCompany: 8
                  version: 1082
                  programName: NETR
                abn: '72001967184'
              requestForDataType:
                startDateTimeStatusRequest: '2024-03-21T19:25:04Z'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DarkAndMedullatedFibreRiskVerificationApiResult'
              example:
                data:
                  transmissionHeader:
                    dateFormatLastRevised: '2020-07-15'
                    dateTransmissionFileCreated: '2016-01-17'
                    countryOfOrigin: AU
                    documentOriginator:
                      organisationCode: ABC
                    currentReceiver:
                      organisationCode: ATW
                    versionNumber: 31
                    softwareIdentifier:
                      softwareCompany: 8
                      version: 1082
                      programName: NETR
                    abn: '72001967184'
                  darkAndMedullatedFibreRiskDetailsCollection:
                    - declaredBreed: A
                      declaredWoolSubCategory: W
                      declaredWoolCategory: P
                      declaredQualifierCodes:
                        - A
                        - H
                        - D
                        - H
                        - S
                        - T
                      declaredQualifierScale: 1
                      isContactingWithExoticBreeds: true
                      isCrutched: true
                      isCrutchedWithin3MonthsOfShearing: false
                      sex: E
                      ageFrom: 12
                      ageTo: 23
                      darkAndMedullatedFibreRiskBroker: 1
                      darkandMedullatedFibreRisk: D
                      certificateIdentity:
                        certificateIDPrefix: 3
                        certificateIDNumber: 499
                        certificateIDSuffix: P
                        certificateIDCD: 7
                      woolBase: 32.14
                      dmfrErrorFields:
                        - '12'
                        - '18'
                        - '9'
                        - '2'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiErrorResult'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred
                status: 400
                detail: ''
                errors:
                  errors:
                    Requests[0].TransmissionHeader.DateFormatLastRevised:
                      - The field DateFormatLastRevised is required
                      - The field DateFormatLastRevised must match regulart expression pattern...
                    Requests[0].TransmissionHeader.CountryOfOrigin:
                      - The field CountryOfOrigin is required
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiErrorResult'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiErrorResult'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiErrorResult'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: Resource not found
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiErrorResult'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
components:
  schemas:
    ApiErrorResult:
      required:
        - status
        - title
      type: object
      properties:
        type:
          type: string
          description: "A URI reference [RFC3986] that identifies the problem type.\r\n\r\nThis specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]). \r\n            \r\nWhen this member is not present, its value is assumed to be \"about:blank\".\r\n\r\ne.g. For 400 Bad Request, the \"type\" value can be \"https://tools.ietf.org/html/rfc9110#section-15.5.1\""
          nullable: true
        title:
          minLength: 1
          type: string
          description: "A short, human-readable summary of the problem type.\r\n\r\nIt SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4).\r\n\r\ne.g. \"One or more validation errors occurred.\""
        status:
          type: integer
          description: The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
          format: int32
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem. e.g. 400, 403, or business relared problem etc.
          nullable: true
        errors:
          $ref: '#/components/schemas/CustomErrors'
      additionalProperties: false
      description: A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.
    ApiMessage:
      type: object
      properties:
        message:
          type: string
          nullable: true
        warningCodes:
          type: array
          items:
            $ref: '#/components/schemas/WarningCode'
          nullable: true
        informationCodes:
          type: array
          items:
            $ref: '#/components/schemas/InformationCode'
          nullable: true
      additionalProperties: false
    ApiResult:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ApiMessage'
        data:
          description: Contains response data. e.g. Auction Catalogue
          nullable: true
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    CatalogueTransmissionType:
      enum:
        - 2
        - 3
        - 5
      type: integer
      description: ' Used to define the types of Catalogue. Only required for requesting Catalouge. Not Applicable for other documents.<br />2: Auction Catalogues<br />3: Private Catalogues<br />5: Auction Catalogue Updates'
      format: int32
    Centre:
      required:
        - centreCode
        - country
      type: object
      properties:
        country:
          $ref: '#/components/schemas/CountryCode'
        centreCode:
          oneOf:
            - $ref: '#/components/schemas/CentreCodeAustralia'
            - $ref: '#/components/schemas/CentreCodeChina'
            - $ref: '#/components/schemas/CentreCodeGermany'
            - $ref: '#/components/schemas/CentreCodeItaly'
            - $ref: '#/components/schemas/CentreCodeNewZealand'
            - $ref: '#/components/schemas/CentreCodeTaiwan'
      additionalProperties: false
      description: "Centre has country and centreCode.\r\n\r\nThe centreCode is one of these below based on the value of country. \r\n\r\nThe mapping of country: centreCode is the following:\r\n            \r\nAU:CentreCodeAustralia\r\n\r\nNZ: CentreNewZealand\r\n\r\nDE: CentreGermany\r\n\r\nIT: CentreItaly\r\n\r\nCN: CentreChina\r\n\r\nTW: CentreTaiwan"
    CentreCodeAustralia:
      enum:
        - A
        - AD
        - AR
        - AU
        - B
        - BA
        - BK
        - BL
        - BM
        - BO
        - BR
        - BT
        - C
        - CA
        - CB
        - CC
        - CL
        - CN
        - CO
        - CR
        - CU
        - CW
        - D
        - DE
        - DO
        - DR
        - E
        - ER
        - ES
        - F
        - G
        - GF
        - GI
        - GN
        - GR
        - GU
        - H
        - HA
        - HB
        - HM
        - HO
        - HY
        - I
        - J
        - JA
        - K
        - KE
        - KH
        - KI
        - KN
        - KT
        - KW
        - KY
        - L
        - LC
        - M
        - MA
        - MB
        - MC
        - ME
        - MG
        - MI
        - MO
        - MR
        - MU
        - 'N'
        - NA
        - ND
        - 'NO'
        - NR
        - OB
        - OR
        - P
        - PA
        - PL
        - Q
        - QU
        - R
        - S
        - SG
        - SH
        - SK
        - SW
        - SY
        - T
        - TE
        - U
        - UR
        - V
        - W
        - WA
        - WG
        - WL
        - WN
        - WR
        - WW
        - X
        - 'Y'
        - YA
        - YM
        - YO
        - Z
        - ZC
        - ZD
        - ZH
        - ZJ
        - ZK
        - ZL
        - ZM
        - ZO
        - ZP
        - ZQ
        - ZR
        - ZT
        - ZV
        - ZW
        - ZX
        - ZY
      type: string
      description: 'This is Centres for Australia. A centre is a town where any activity connected with the wool industry takes place. The codes used in transmissions are those defined in the Australian Wool Selling Regulation.<br />A: Australia - ADELAIDE<br />AD: Australia - Ardlethan<br />AR: Australia - Armidale (NSW)<br />AU: Australia - AUSTRALIA (AWEX internal only)<br />B: Australia - BRISBANE<br />BA: Australia - Benalla<br />BK: Australia - Bourke<br />BL: Australia - Ballarat<br />BM: Australia - Barham<br />BO: Australia - Boorowa<br />BR: Australia - Bordertown<br />BT: Australia - Bathurst<br />C: Australia - Cooma<br />CA: Australia - Casterton<br />CB: Australia - Coonabarabran<br />CC: Australia - Culcairn<br />CL: Australia - Coleraine<br />CN: Australia - Condoblin<br />CO: Australia - Cootamundra<br />CR: Australia - Corowa<br />CU: Australia - Cunnamulla<br />CW: Australia - Crookwell<br />D: Australia - Bendigo<br />DE: Australia - Deniliquin<br />DO: Australia - Dubbo<br />DR: Australia - Canowindra<br />E: Australia - Echuca<br />ER: Australia - Euroa<br />ES: Australia - Esperance<br />F: Australia - FREMANTLE<br />G: Australia - GEELONG<br />GF: Australia - Grenfell<br />GI: Australia - Glenn Innes<br />GN: Australia - Gunning<br />GR: Australia - Griffith<br />GU: Australia - Guyra<br />H: Australia - Hobart<br />HA: Australia - Harden<br />HB: Australia - Holbrook<br />HM: Australia - Hamilton<br />HO: Australia - Horsham<br />HY: Australia - Hay<br />I: Australia - Narrabri<br />J: Australia - Parkes<br />JA: Australia - Jamestown<br />K: Australia - Warracknabeal<br />KE: Australia - Kerang<br />KH: Australia - Keith<br />KI: Australia - Kangaroo Island<br />KN: Australia - Kingston<br />KT: Australia - Katanning<br />KW: Australia - Wagga Wagga<br />KY: Australia - Kyneton<br />L: Australia - LAUNCESTON<br />LC: Australia - Lane Cove (AWEX internal only)<br />M: Australia - MELBOURNE<br />MA: Australia - Mansfield<br />MB: Australia - Murray Bridge<br />MC: Australia - Macarthur<br />ME: Australia - Melton<br />MG: Australia - Mount Gambier<br />MI: Australia - Mildura<br />MO: Australia - Moree<br />MR: Australia - Maryborough<br />MU: Australia - Mudgee<br />N: Australia - NEWCASTLE<br />NA: Australia - Narrandera<br />ND: Australia - Goondiwindi<br />NO: Australia - Northam<br />NR: Australia - Naracoorte<br />OB: Australia - Oberon<br />OR: Australia - Orange<br />P: Australia - Portland<br />PA: Australia - Cowra<br />PL: Australia - Port Lincoln<br />Q: Australia - Yarrawonga<br />QU: Australia - Queanbeyan<br />R: Australia - GOULBURN<br />S: Australia - SYDNEY<br />SG: Australia - St George<br />SH: Australia - Shepparton<br />SK: Australia - Skipton<br />SW: Australia - Swan Hill<br />SY: Australia - Seymour<br />T: Australia - Inverell<br />TE: Australia - Temora<br />U: Australia - Auburn<br />UR: Australia - Uralla<br />V: Australia - Forbes<br />W: Australia - Tamworth<br />WA: Australia - Warren<br />WG: Australia - Walgett<br />WL: Australia - Walcha<br />WN: Australia - Wellington<br />WR: Australia - Wangaratta<br />WW: Australia - West Wyalong<br />X: Australia - Ararat<br />Y: Australia - Albury<br />YA: Australia - Yass<br />YM: Australia - Yarram<br />YO: Australia - Young<br />Z: Australia - Albany<br />ZC:Christchurch - New Zealand<br />ZD: Dunedin - New Zealand<br />ZH: Blumenthal - Germany<br />ZJ: Biella - Italy<br />ZK: Grisignano - Italy<br />ZL: Mosgiel - New Zealand<br />ZM: Nanjing - China<br />ZO: Keelung - Taiwan<br />ZP: Shanghai - China<br />ZQ: Qingdao - China<br />ZR: Zhangjiagang - China<br />ZT: Timaru - New Zealand<br />ZV: Invercargill - New Zealand<br />ZW:Wellington - New Zealand<br />ZX: Napier – New Zealand<br />ZY: Ashburton – New Zealand'
    CentreCodeChina:
      enum:
        - NA
        - SH
        - QI
        - ZH
      type: string
      description: 'This is Centres for China. A centre is a town where any activity connected with the wool industry takes place. The codes used in transmissions are those defined in the Australian Wool Selling Regulation.<br />NA: Nanjing - China<br />SH: Shanghai - China<br />QI: Qingdao - China<br />ZH: Zhangjiagang - China'
    CentreCodeGermany:
      enum:
        - BL
      type: string
      description: 'This is Centres for Germany. A centre is a town where any activity connected with the wool industry takes place. The codes used in transmissions are those defined in the Australian Wool Selling Regulation.<br />BL: Blumenthal - Germany'
    CentreCodeItaly:
      enum:
        - BI
        - GR
      type: string
      description: 'This is Centres for Italy. A centre is a town where any activity connected with the wool industry takes place. The codes used in transmissions are those defined in the Australian Wool Selling Regulation.<br />BI: Biella - Italy<br />GR: Grisignano - Italy'
    CentreCodeNewZealand:
      enum:
        - A
        - AW
        - B
        - BL
        - BT
        - C
        - CV
        - D
        - F
        - FA
        - G
        - GD
        - GO
        - HA
        - HS
        - I
        - J
        - K
        - KA
        - KP
        - L
        - LO
        - LU
        - M
        - MA
        - MK
        - MT
        - MU
        - 'N'
        - NE
        - O
        - OH
        - OI
        - OM
        - OT
        - P
        - PT
        - PU
        - R
        - RG
        - RI
        - S
        - SA
        - SH
        - SY
        - T
        - TA
        - TE
        - TH
        - TP
        - U
        - V
        - W
        - WH
        - WI
        - WR
        - WT
        - WU
        - X
        - 'Y'
        - YP
        - Z
      type: string
      description: 'This is Centres for New Zealand. A centre is a town where any activity connected with the wool industry takes place. The codes used in transmissions are those defined in the Australian Wool Selling Regulation.<br />A: New Zealand - Auckland<br />AW: New Zealand - Awatoto<br />B: New Zealand - Cambridge<br />BL: New Zealand - Blenheim<br />BT: New Zealand - Bunnythorpe<br />C: New Zealand - Christchurch<br />CV: New Zealand - Clive<br />D: New Zealand - Dunedin<br />F: New Zealand - Feilding<br />FA: New Zealand - Fairlie<br />G: New Zealand - Gisborne<br />GD: New Zealand - Geraldine<br />GO: New Zealand - Gore<br />HA: New Zealand - Hawera<br />HS: New Zealand - Hastings<br />I: New Zealand - Invercargill<br />J: New Zealand - Tapanui<br />K: New Zealand - Te Kuiti<br />KA: New Zealand - Kakariki<br />KP: New Zealand - Kaiapoi<br />L: New Zealand - Mosgiel<br />LO: New Zealand - Longburn<br />LU: New Zealand - Lumsden<br />M: New Zealand - Masterton<br />MA: New Zealand - Mangatinoka<br />MK: New Zealand - Motueka<br />MT: New Zealand - Milton<br />MU: New Zealand - Mataura<br />N: New Zealand - Napier<br />NE: New Zealand - Nelson<br />O: New Zealand - Oamaru<br />OH: New Zealand - Ohinewai<br />OI: New Zealand - Ohai<br />OM: New Zealand - Omakau<br />OT: New Zealand - Otorohonga<br />P: New Zealand - Palmerston North<br />PT: New Zealand - Pahiatua<br />PU: New Zealand - Putaruru<br />R: New Zealand - Rotorua<br />RG: New Zealand - Rangiora<br />RI: New Zealand - Riwaka<br />S: New Zealand - Ashburton<br />SA: New Zealand - Saltwater Creek<br />SH: New Zealand - Shannon<br />SY: New Zealand - Sydney<br />T: New Zealand - Timaru<br />TA: New Zealand - Tapanui<br />TE: New Zealand - TeAnau<br />TH: New Zealand - Taihape<br />TP: New Zealand - Te Puke<br />U: New Zealand - Taumaruniu<br />V: New Zealand - Dannevirke<br />W: New Zealand - Wellington<br />WH: New Zealand - Whakatu<br />WI: New Zealand - Whakatu Industrial Park<br />WR: New Zealand - Wairoa<br />WT: New Zealand - Winton<br />WU: New Zealand - Waikuku<br />X: New Zealand - Wanganui<br />Y: New Zealand - Whangarei<br />YP: New Zealand - Waipukurau<br />Z: New Zealand - Taupo'
    CentreCodeTaiwan:
      enum:
        - KE
      type: string
      description: 'This is Centres for Taiwan. A centre is a town where any activity connected with the wool industry takes place. The codes used in transmissions are those defined in the Australian Wool Selling Regulation.<br />KE: Keelung - Taiwan'
    CertificateIDPrefix:
      enum:
        - 2
        - 3
        - 6
      type: integer
      description: '2: Sydney Laboratory<br />3: Melbourne Laboratory<br />6: Fremantle Laboratory'
      format: int32
    CertificateIDSuffix:
      enum:
        - B
        - C
        - D
        - F
        - I
        - J
        - L
        - M
        - 'N'
        - Q
        - P
        - R
        - W
        - 'Y'
      type: string
      description: 'B: Bulk Class<br />C: Colour<br />D: PTC (Pre-Sale Test Certificate – Other Grower Lot)<br />F: Premium Test<br />I: Subjectively Appraised Interlot<br />J: Combination - Yield & Micron, Length & Strength, Colour<br />L: Length & Strength<br />M: Objectively Matched Lot<br />N: Objectively matched Interlot<br />Q: Bulk Class – Quality Managed<br />P: PTC (Pre-sale Test Certificate - Classed Grower Lot)<br />R: Guidance Report<br />W: Scoured Wool<br />Y: Post sale Core Test'
    CertificateIdentity:
      required:
        - certificateIDCD
        - certificateIDNumber
        - certificateIDPrefix
        - certificateIDSuffix
      type: object
      properties:
        certificateIDPrefix:
          $ref: '#/components/schemas/CertificateIDPrefix'
        certificateIDNumber:
          maxLength: 8
          minLength: 1
          type: integer
          format: int32
        certificateIDSuffix:
          $ref: '#/components/schemas/CertificateIDSuffix'
        certificateIDCD:
          maxLength: 1
          minLength: 1
          type: integer
          format: int32
      additionalProperties: false
    ClassForOneOfReferencesToBeDeleted:
      type: object
      properties:
        useNetworkDateTimeRequestForDataType:
          $ref: '#/components/schemas/UseNetworkDateTimeRequestForDataType'
        dateTimeRangeRequestForDataType:
          $ref: '#/components/schemas/DateTimeRangeRequestForDataType'
        woolSaleRequestForDataType:
          $ref: '#/components/schemas/WoolSaleRequestForDataType'
      additionalProperties: false
    ClassToBeExcluded:
      enum:
        - LotHeaderPricing
        - LotHeaderAwexData
        - LotHeaderVendorDeclaration
        - ColourDetails
        - InterlotComponentBaleHeader
        - BaleIdentification
        - FibreDiameterHistogramHeader
        - FibreDiameterHistogramDetails
      type: string
    CountryCode:
      enum:
        - AU
        - NZ
        - DE
        - IT
        - CN
        - TW
      type: string
      description: 'A code for the country in which the transmission was created. Country Code using ISO 3166-1 standard<br />AU: Australia<br />NZ: New Zealand<br />DE: Germany<br />IT: Italy<br />CN: China<br />TW: Taiwan'
    CustomErrors:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
            nullable: true
          description: 'Dictionary of errors in <PropertyName, ErrorDetails[]> format. e.g. errors: { "name": ["Product name is required"], "category": ["Category name cannot be longer than 20 characters."]  }'
          nullable: true
        errorCodes:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCode'
          nullable: true
      additionalProperties: false
    DarkAndMedullatedFibreRisk:
      enum:
        - E
        - 'N'
        - D
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
      type: string
      description: 'E: Error in Processing<br />N: Not Applicable<br />D: Not Declared<br />1: Risk Level 1 (lowest)<br />2: Risk Level 2<br />3: Risk Level 3<br />4: Risk Level 4<br />5: Risk Level 5<br />6: Risk Level 6'
    DarkAndMedullatedFibreRiskBroker:
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      type: integer
      description: '1: Risk Level 1 (lowest)<br />2: Risk Level 2<br />3: Risk Level 3<br />4: Risk Level 4<br />5: Risk Level 5<br />6: Risk Level 6'
      format: int32
    DarkAndMedullatedFibreRiskDetails:
      required:
        - ageFrom
        - declaredBreed
        - declaredWoolCategory
        - declaredWoolSubCategory
        - isContactingWithExoticBreeds
        - isCrutched
        - sex
      type: object
      properties:
        declaredBreed:
          $ref: '#/components/schemas/DeclaredBreed'
        declaredWoolSubCategory:
          $ref: '#/components/schemas/DeclaredWoolSubCategory'
        declaredWoolCategory:
          $ref: '#/components/schemas/DeclaredWoolCategory'
        declaredQualifierCodes:
          type: array
          items:
            $ref: '#/components/schemas/DeclaredQualifierCode'
          nullable: true
        declaredQualifierScale:
          $ref: '#/components/schemas/DeclaredQualifierScale'
        isContactingWithExoticBreeds:
          maxLength: 5
          minLength: 4
          type: boolean
          description: "A boolean value to indicate whether it contact with exotic breeds.\r\n            \r\ntrue: contact with exotic breeds.\r\n            \r\nfalse: not contact with exotic breeds."
        isCrutched:
          maxLength: 5
          minLength: 4
          type: boolean
          description: "A boolean value to indicate whether it is crutched.\r\n\r\ntrue: crutched.\r\n            \r\nfalse: not crutched."
        isCrutchedWithin3MonthsOfShearing:
          maxLength: 5
          minLength: 4
          type: boolean
          description: "A boolean value to indicate whether crutching within 3 months of shearing.\r\n            \r\ntrue: yes.\r\n            \r\nfalse: no."
          nullable: true
        sex:
          $ref: '#/components/schemas/Sex'
        ageFrom:
          pattern: '-?\d{1,2}'
          type: integer
          description: Required numeric field for minimum age.
          format: int32
        ageTo:
          pattern: '-?\d{1,2}'
          type: integer
          description: Optional numeric field for maximum age.
          format: int32
          nullable: true
        darkAndMedullatedFibreRiskBroker:
          $ref: '#/components/schemas/DarkAndMedullatedFibreRiskBroker'
        darkandMedullatedFibreRisk:
          $ref: '#/components/schemas/DarkAndMedullatedFibreRisk'
        certificateIdentity:
          $ref: '#/components/schemas/CertificateIdentity'
        woolBase:
          pattern: ^-?\d{1,2}\.\d{2}$
          type: number
          format: double
          nullable: true
        dmfrErrorFields:
          type: array
          items:
            type: string
          description: A list of DMFR Error Field, each field should be a numeric string with up to two digits.
          nullable: true
      additionalProperties: false
    DarkAndMedullatedFibreRiskVerification:
      required:
        - transmissionHeader
      type: object
      properties:
        transmissionHeader:
          $ref: '#/components/schemas/TransmissionHeader'
        transferConfig:
          $ref: '#/components/schemas/TransferConfig'
        darkAndMedullatedFibreRiskDetailsCollection:
          type: array
          items:
            $ref: '#/components/schemas/DarkAndMedullatedFibreRiskDetails'
          nullable: true
      additionalProperties: false
    DarkAndMedullatedFibreRiskVerificationApiResult:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ApiMessage'
        data:
          $ref: '#/components/schemas/DarkAndMedullatedFibreRiskVerification'
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    DateTimeRangeRequestForDataType:
      required:
        - startDateTimeStatusRequest
      type: object
      properties:
        startDateTimeStatusRequest:
          maxLength: 20
          minLength: 1
          pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
          type: string
          description: Date and Time value in ISO 8601 standard UTC format. e.g. 2024-03-21T19:25:04Z
          format: date-time
        endDateTimeStatusRequest:
          maxLength: 20
          minLength: 1
          pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
          type: string
          description: Date and Time value in ISO 8601 standard UTC format. e.g. 2024-03-21T19:25:04Z
          format: date-time
          nullable: true
      additionalProperties: false
    DeclaredBreed:
      enum:
        - A
        - M
        - X
        - D
        - T
        - R
      type: string
      description: 'A: Australian Superfine<br />M: Merino<br />X: Crossbred<br />D: Downs<br />T: Carpet<br />R: Sheds Fibres'
    DeclaredQualifierCode:
      enum:
        - T
        - H
        - M
        - S
        - C
        - J
        - A
        - K
        - Q
        - E
        - 'N'
        - R
        - G
        - D
        - V
        - P
        - 'Y'
        - F
        - U
      type: string
      description: 'Optional enum type for qualifier code.<br />T: Qualifier not required<br />H: Unscourable colour<br />M: Scourable colour/creamy<br />S: Dark Stain<br />C: Cotts<br />J: Jowls<br />A: Dermatitis<br />K: Kemp / Medullated<br />Q: Dags<br />E: Necks (Not Scaled)<br />N: Water Stain<br />R: Brands<br />G: Doggy (Not Scaled)<br />D: Mud<br />V: Skin pieces<br />P: Shanks<br />Y: Black & Grey<br />F: Soft Cotts<br />U: Sweat/Frib'
    DeclaredQualifierScale:
      enum:
        - 0
        - 1
        - 2
        - 3
      type: integer
      description: '0: No scale/qualifier code is T<br />1: Light/Odd<br />2: Medium<br />3: Heavy/Line of…'
      format: int32
    DeclaredWoolCategory:
      enum:
        - F
        - P
        - B
        - C
        - Z
      type: string
      description: 'F: Fleece<br />P: Pieces<br />B: Bellies<br />C: Crutchings<br />Z: Locks'
    DeclaredWoolSubCategory:
      enum:
        - W
        - L
        - U
        - K
        - G
        - O
        - 'N'
        - T
      type: string
      description: 'W: Combing Weaners & Lambs<br />L: Carding Lambs<br />U: Plucked & Dead<br />K: Shorn from Skins<br />G: Fellmongered<br />O: Overgrown<br />N: Non-conforming lot<br />T: Not required'
    ErrorCode:
      enum:
        - DOXCT
        - INVTC
        - INVFR
        - INVAC
        - INVCR
        - INVDO
        - INVSO
        - INVEX
      type: string
      description: 'A code to indicate the different types of errors.<br />DOXCT: Document originator does not match current transmitter.<br />INVTC: Invalid transfer config. All data rejected.<br />INVFR: Invalid/missing FinalReceiverList record. All data rejected.<br />INVAC: Invalid sale aann/nn dd/mm/yy ooooo. All data rejected.<br />INVCR: Current receiver not awtm. All data rejected.<br />INVDO: Invalid document originator code aaaaa. Data accepted.<br />INVSO: Warning! Invalid selling org AAAAA using doc orig AAAAA.<br />INVEX: Invalid excluded record.'
    ExcludedClass:
      required:
        - classToBeExcluded
      type: object
      properties:
        classToBeExcluded:
          $ref: '#/components/schemas/ClassToBeExcluded'
        subClassToBeExcluded:
          $ref: '#/components/schemas/SubClassToBeExcluded'
      additionalProperties: false
    InformationCode:
      enum:
        - OK
      type: string
      description: "A code to indicate the information.\r\n\r\nFor AC, PC LI and GI transmissions, one record will be sent for each Wool Sale Header Lots received.\r\n\r\nOK - aaaaaDATA RECEIVED OK FOR aann/nn dd/mm/yy ooooo LOTS nnnn\r\n\r\nWhere aann/nn = sale number/season\r\n    \r\ndd/mm/yy = sale date\r\n    \r\nooooo = selling organisation\r\n    \r\nnnnnn = number of lots\r\n    \r\nReason - You have sent data to the network and it has been received with no communication or transmission errors.\r\n\r\nAction - None.\r\n\r\nOR\r\n\r\nFor all other types of transmissions, one record will be sent for each transmission file received.\r\n\r\nOK - ALL aaaaa DATA RECEIVED OK\r\n\r\nReason - You have sent data to the network and it has been received with no communication or transmission errors.\r\n\r\nAction - None."
    Organisation:
      required:
        - organisationCode
      type: object
      properties:
        organisationCode:
          maxLength: 3
          minLength: 1
          type: string
        centre:
          $ref: '#/components/schemas/Centre'
      additionalProperties: false
    RequestForData:
      required:
        - requestForDataType
        - transmissionHeader
      type: object
      properties:
        transmissionHeader:
          $ref: '#/components/schemas/TransmissionHeader'
        requestForDataType:
          oneOf:
            - $ref: '#/components/schemas/UseNetworkDateTimeRequestForDataType'
            - $ref: '#/components/schemas/DateTimeRangeRequestForDataType'
      additionalProperties: false
    RequestTypeForData:
      enum:
        - 1
        - 3
        - 4
      type: integer
      description: '1: Private Data Request<br />3: Data Re-Request<br />4: Broadcast Data Request'
      format: int32
    SaleIdentity:
      required:
        - saleNumber
        - sellingCentreType
      type: object
      properties:
        sellingCentreType:
          maxLength: 2
          minLength: 1
          type: string
          description: "SellingCentre/Type can be one of the following code:\r\n            \r\nSellingCentre/Type (New Zealand):\r\n            \r\nC: Christchurch; N: Napier.\r\n            \r\nSellingCentre/Type (Australia):\r\n            \r\nA: Adelaide; AU: Australia; B: Brisbane; F: Fremantle; G: Geelong; L: Launceston; M: Melbourne; N: Newcastle; R: Goulburn; S: Sydney; PS: Private Sales; T: Auctions Plus Sales."
        saleNumber:
          maxLength: 2
          minLength: 1
          pattern: '-?\d{1,2}'
          type: integer
          format: int32
      additionalProperties: false
      description: "A group field of SellingCentre/Type and Sale Number\r\n            \r\nFrom: The current value that the Sale Identity is to be changed from.\r\n            \r\nTo: The new value that the Sale Identity is to be changed to."
    Sex:
      enum:
        - E
        - W
        - R
        - M
      type: string
      description: 'E: Ewes<br />W: Wethers<br />R: Rams<br />M: Mixed'
    SoftwareCompany:
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
      type: integer
      description: '1: Talman<br />2: Symbotic<br />3: Jumbuck/Datacon<br />4: Jemalong<br />5: NA - no value<br />6: Modiano<br />7: AWH<br />6: AWTA'
      format: int32
    SoftwareIdentifier:
      type: object
      properties:
        softwareCompany:
          $ref: '#/components/schemas/SoftwareCompany'
        version:
          pattern: '-?\d{1,4}'
          type: integer
          description: Version no. e.g. 2400
          format: int32
          nullable: true
        programName:
          maxLength: 4
          minLength: 1
          type: string
          nullable: true
      additionalProperties: false
    SubClassToBeExcluded:
      enum:
        - A
        - B
        - C
        - D
        - E
        - F
        - H
        - I
        - J
        - K
        - L
        - M
        - 'N'
        - P
        - R
        - T
        - U
        - V
        - W
        - X
        - 'Y'
        - Z
      type: string
      description: 'A: First record of one type<br />B: Second record of that type<br />C: Colour Certificate record<br />D: Detail record<br />E: Scoured Yield Extension<br />F: Premium Certificate record<br />H: Header record<br />I: Subjective Interlot Certificate record<br />J: Combination Certificate record<br />K: Length and Strength Combination Certificate record<br />L: Length and Strength Certificate Record<br />M: Objectively Matched Lot Certificate Record<br />N: Objectively Matched Interlot Certificate Record<br />P: Core Test Certificate Record<br />R: Guidance Report Details<br />T: Trailer record<br />U: Length After Carding Test Details<br />V:Conditioning Test Details<br />W: Scoured Test Details<br />X: Colour Combination Certificate Record<br />Y: Post sale Core Test Detail<br />Z: Adjustment Note Details'
    TransferConfig:
      required:
        - transferType
      type: object
      properties:
        transferType:
          $ref: '#/components/schemas/TransferType'
        finalReceiverList:
          type: array
          items:
            $ref: '#/components/schemas/Organisation'
          nullable: true
      additionalProperties: false
      description: "Used to identify document transfer type: Restrict, Unrestrict, and Exlcude.\r\n\r\nOnly used for data retrieval. Do not include it in the response."
    TransferType:
      enum:
        - Unrestrict
        - Restrict
        - Exclude
      type: string
      description: 'Unrestrict: Send document to all members<br />Restrict: Send document to appointed members<br />Exclude: Send to all members excluding the appointed members'
    TransmissionHeader:
      required:
        - abn
        - countryOfOrigin
        - currentReceiver
        - dateFormatLastRevised
        - dateTransmissionFileCreated
        - documentOriginator
      type: object
      properties:
        dateFormatLastRevised:
          maxLength: 10
          minLength: 1
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD).
          format: date
        dateTransmissionFileCreated:
          maxLength: 10
          minLength: 1
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD).
          format: date
        countryOfOrigin:
          $ref: '#/components/schemas/CountryCode'
        documentOriginator:
          $ref: '#/components/schemas/Organisation'
        currentReceiver:
          $ref: '#/components/schemas/Organisation'
        versionNumber:
          pattern: '-?\d{1,2}'
          type: integer
          description: Two digits. e.g. 99
          format: int32
          nullable: true
        softwareIdentifier:
          $ref: '#/components/schemas/SoftwareIdentifier'
        abn:
          maxLength: 11
          minLength: 1
          pattern: ^[0-9]+$
          type: string
          description: Australian Business Number, 11 digits string
        classForOneOfReferencesToBeDeleted:
          $ref: '#/components/schemas/ClassForOneOfReferencesToBeDeleted'
      additionalProperties: false
    UseNetworkDateTimeRequestForDataType:
      required:
        - isUsingNetworkDateTime
      type: object
      properties:
        isUsingNetworkDateTime:
          maxLength: 5
          minLength: 4
          type: boolean
          description: "A boolean value to indicate whether to use network datetime.\r\n\r\ntrue: use network datetime.\r\n\r\nfalse: not use."
      additionalProperties: false
    WarningCode:
      enum:
        - '11'
        - '12'
        - '13'
        - '18'
        - '19'
        - '20'
        - '24'
        - DRVnn
      type: string
      description: 'A code to indicate the different types of errors.<br />11: Weight Note suffix is not numeric or has been omitted.<br />12: Number of bales is invalid or has been omitted.<br />13: Sale identification has been omitted.<br />18: Invalid Gross weight.<br />19: Invalid Tare weight.<br />20: Invalid Centre/Client code on pre-sale test request.<br />24: Incorrect PCTR Hash total.<br />DRVnn: Dark and Medullated Fibre Risk error where nn is the field number in error.'
    WoolSaleRequestForDataType:
      required:
        - requestType
      type: object
      properties:
        catalogueTransmissionType:
          $ref: '#/components/schemas/CatalogueTransmissionType'
        saleIdentity:
          $ref: '#/components/schemas/SaleIdentity'
        organisationRequested:
          $ref: '#/components/schemas/Organisation'
        saleDateRequested:
          maxLength: 10
          minLength: 1
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD).
          format: date
          nullable: true
        requestType:
          $ref: '#/components/schemas/RequestTypeForData'
        woolTypeGroup:
          $ref: '#/components/schemas/WoolTypeGroup'
        excludedClasses:
          maxItems: 80
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/ExcludedClass'
          description: "Cataglouge classes and sub-classes to be excluded in the request.\r\n\r\nOnly required for request for Catalogue. Not applicable for other documents."
          nullable: true
        season:
          pattern: '-?\d{1,2}'
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    WoolTypeGroup:
      enum:
        - MFLC
        - MSKT
        - XBFS
        - ODDS
      type: string
      description: 'A code to indicate which section of the sale that lot belongs.<br />MFLC: Merino fleece types<br />MSKT: Merino fleece types<br />XBFS: Merino fleece types<br />ODDS: Merino fleece types'
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Access Token that is added in the Authorization header of the HTTP request. Example: "Authorization: Bearer {token}". The JWT serves as a credential that proves the identity of the client to the server.'
      name: Authorization
      in: header
    oauth2:
      type: oauth2
      description: Authentication for client applications by providing Client ID and Client Secret for an JWT Access Token.
      flows:
        clientCredentials:
          tokenUrl: /auth-server/oauth/token
          scopes: {}
security:
  - Bearer: []
