openapi: 3.0.1
info:
  title: WIEDPUG API
  description: API Documentation for the WIEDPUG Network
  termsOfService: https://wiedpug.github.io/wiedpug
  contact:
    name: WIEDPUG Team
    url: https://wiedpug.github.io/wiedpug
    email: changethis@email.com
  license:
    name: Applicable License
    url: https://wiedpug.github.io/wiedpug
  version: v0.0
paths:
  /v0/texts:
    post:
      tags:
        - Texts
      summary: Texts
      description: Used to provide texts
      operationId: CreateTexts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Texts'
            example:
              textList:
                - transmissionHeader:
                    dateFormatLastRevised: '2020-07-15'
                    dateTransmissionFileCreated: '2016-01-17'
                    countryOfOrigin: AU
                    documentOriginator:
                      organisationCode: ABC
                    currentReceiver:
                      organisationCode: ATW
                    versionNumber: 31
                    softwareIdentifier:
                      softwareCompany: 1
                      version: 1082
                      programName: NETR
                    abn: '72001967184'
                  transferConfig:
                    transferType: Unrestrict
                  comments:
                    - text: Order is paid.
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResult'
              example:
                isSuccessful: true
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred
                status: 400
                detail: ''
                errors:
                  TransmissionHeader.DateFormatLastRevised:
                    - The field DateFormatLastRevised is required
                    - >-
                      The field DateFormatLastRevised must match regulart
                      expression pattern...
                  TransmissionHeader.CountryOfOrigin:
                    - The field CountryOfOrigin is required
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: >-
                  https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
  /v0/texts/data:
    post:
      tags:
        - Texts
      summary: Retrieves the texts
      operationId: RequestForTexts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestForTexts'
            example:
              saleIdentity:
                sellingCentreType: AU_M
                saleNumber: 18
              organisationRequested: AWNF
              saleDateRequested: '2023-10-31'
              useNetworkDateTime: false
              requestType: 4
              woolTypeGroup: MFLC
              season: 23
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextsApiResult'
              example:
                isSuccessful: true
                data:
                  textList:
                    - transmissionHeader:
                        dateFormatLastRevised: '2020-07-15'
                        dateTransmissionFileCreated: '2016-01-17'
                        countryOfOrigin: AU
                        documentOriginator:
                          organisationCode: ABC
                        currentReceiver:
                          organisationCode: ATW
                        versionNumber: 31
                        softwareIdentifier:
                          softwareCompany: 1
                          version: 1082
                          programName: NETR
                        abn: '72001967184'
                      comments:
                        - text: Order is paid.
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred
                status: 400
                detail: ''
                errors:
                  Requests[0].TransmissionHeader.DateFormatLastRevised:
                    - The field DateFormatLastRevised is required
                    - >-
                      The field DateFormatLastRevised must match regulart
                      expression pattern...
                  Requests[0].TransmissionHeader.CountryOfOrigin:
                    - The field CountryOfOrigin is required
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: Resource not found
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: >-
                  https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
components:
  schemas:
    ApiResult:
      required:
        - isSuccessful
      type: object
      properties:
        isSuccessful:
          type: boolean
          description: Indicator if the request has been successfully processed.
        message:
          type: string
          description: Contains information about the response if applicable.
          nullable: true
        data:
          description: Contains response data. e.g. Auction Catalogue
          nullable: true
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    Centre:
      required:
        - centreCode
        - country
      type: object
      properties:
        country:
          $ref: '#/components/schemas/CountryCode'
        centreCode:
          oneOf:
            - $ref: '#/components/schemas/CentreCodeAustralia'
            - $ref: '#/components/schemas/CentreCodeBelgium'
            - $ref: '#/components/schemas/CentreCodeChina'
            - $ref: '#/components/schemas/CentreCodeFrance'
            - $ref: '#/components/schemas/CentreCodeGermany'
            - $ref: '#/components/schemas/CentreCodeItaly'
            - $ref: '#/components/schemas/CentreCodeNetherlands'
            - $ref: '#/components/schemas/CentreCodeNewZealand'
            - $ref: '#/components/schemas/CentreCodeSouthAfrica'
            - $ref: '#/components/schemas/CentreCodeTaiwan'
            - $ref: '#/components/schemas/CentreCodeUnitedKingdomOfGreatBritain'
            - $ref: '#/components/schemas/CentreCodeUnitedStatesOfAmerica'
      additionalProperties: false
      description: "Centre has country and centreCode.\r\nThe centreCode is one of these below based on the value of country. \r\nThe mapping of country: centreCode is the following:\r\n            \r\nAU:CentreCodeAustralia\r\n\r\nNZ: CentreNewZealand\r\n\r\nFR: CentreFrance\r\n\r\nZA: CentreSouthAfrica\r\n\r\nBE: CentreBelgium\r\n\r\nGB: CentreUnitedKingdomofGreatBritain\r\n\r\nDE: CentreGermany\r\n\r\nIT: CentreItaly\r\n\r\nNL: CentreNetherlands\r\n\r\nCN: CentreChina\r\n\r\nTW: CentreTaiwan\r\n\r\nUS: CentreUSA"
    CentreCodeAustralia:
      enum:
        - A
        - AD
        - AR
        - AU
        - B
        - BA
        - BK
        - BL
        - BM
        - BO
        - BR
        - BT
        - C
        - CA
        - CB
        - CC
        - CL
        - CN
        - CO
        - CR
        - CU
        - CW
        - D
        - DE
        - DO
        - DR
        - E
        - ER
        - ES
        - F
        - G
        - GF
        - GI
        - GN
        - GR
        - GU
        - H
        - HA
        - HB
        - HM
        - HO
        - HY
        - I
        - J
        - JA
        - K
        - KE
        - KH
        - KI
        - KN
        - KT
        - KW
        - KY
        - L
        - LC
        - M
        - MA
        - MB
        - MC
        - ME
        - MG
        - MI
        - MO
        - MR
        - MU
        - 'N'
        - NA
        - ND
        - 'NO'
        - NR
        - OB
        - OR
        - P
        - PA
        - PL
        - Q
        - QU
        - R
        - S
        - SG
        - SH
        - SK
        - SW
        - SY
        - T
        - TE
        - U
        - UR
        - V
        - W
        - WA
        - WG
        - WL
        - WN
        - WR
        - WW
        - X
        - 'Y'
        - YA
        - YM
        - YO
        - Z
      type: string
      description: >-
        This is Centres for Australia. A centre is a town where any activity
        connected with the wool industry takes place. The codes used in
        transmissions are those defined in the Australian Wool Selling
        Regulation.<br />A: Australia - ADELAIDE<br />AD: Australia -
        Ardlethan<br />AR: Australia - Armidale (NSW)<br />AU: Australia -
        AUSTRALIA (AWEX internal only)<br />B: Australia - BRISBANE<br />BA:
        Australia - Benalla<br />BK: Australia - Bourke<br />BL: Australia -
        Ballarat<br />BM: Australia - Barham<br />BO: Australia - Boorowa<br
        />BR: Australia - Bordertown<br />BT: Australia - Bathurst<br />C:
        Australia - Cooma<br />CA: Australia - Casterton<br />CB: Australia -
        Coonabarabran<br />CC: Australia - Culcairn<br />CL: Australia -
        Coleraine<br />CN: Australia - Condoblin<br />CO: Australia -
        Cootamundra<br />CR: Australia - Corowa<br />CU: Australia -
        Cunnamulla<br />CW: Australia - Crookwell<br />D: Australia - Bendigo<br
        />DE: Australia - Deniliquin<br />DO: Australia - Dubbo<br />DR:
        Australia - Canowindra<br />E: Australia - Echuca<br />ER: Australia -
        Euroa<br />ES: Australia - Esperance<br />F: Australia - FREMANTLE<br
        />G: Australia - GEELONG<br />GF: Australia - Grenfell<br />GI:
        Australia - Glenn Innes<br />GN: Australia - Gunning<br />GR: Australia
        - Griffith<br />GU: Australia - Guyra<br />H: Australia - Hobart<br
        />HA: Australia - Harden<br />HB: Australia - Holbrook<br />HM:
        Australia - Hamilton<br />HO: Australia - Horsham<br />HY: Australia -
        Hay<br />I: Australia - Narrabri<br />J: Australia - Parkes<br />JA:
        Australia - Jamestown<br />K: Australia - Warracknabeal<br />KE:
        Australia - Kerang<br />KH: Australia - Keith<br />KI: Australia -
        Kangaroo Island<br />KN: Australia - Kingston<br />KT: Australia -
        Katanning<br />KW: Australia - Wagga Wagga<br />KY: Australia -
        Kyneton<br />L: Australia - LAUNCESTON<br />LC: Australia - Lane Cove
        (AWEX internal only)<br />M: Australia - MELBOURNE<br />MA: Australia -
        Mansfield<br />MB: Australia - Murray Bridge<br />MC: Australia -
        Macarthur<br />ME: Australia - Melton<br />MG: Australia - Mount
        Gambier<br />MI: Australia - Mildura<br />MO: Australia - Moree<br />MR:
        Australia - Maryborough<br />MU: Australia - Mudgee<br />N: Australia -
        NEWCASTLE<br />NA: Australia - Narrandera<br />ND: Australia -
        Goondiwindi<br />NO: Australia - Northam<br />NR: Australia -
        Naracoorte<br />OB: Australia - Oberon<br />OR: Australia - Orange<br
        />P: Australia - Portland<br />PA: Australia - Cowra<br />PL: Australia
        - Port Lincoln<br />Q: Australia - Yarrawonga<br />QU: Australia -
        Queanbeyan<br />R: Australia - GOULBURN<br />S: Australia - SYDNEY<br
        />SG: Australia - St George<br />SH: Australia - Shepparton<br />SK:
        Australia - Skipton<br />SW: Australia - Swan Hill<br />SY: Australia -
        Seymour<br />T: Australia - Inverell<br />TE: Australia - Temora<br />U:
        Australia - Auburn<br />UR: Australia - Uralla<br />V: Australia -
        Forbes<br />W: Australia - Tamworth<br />WA: Australia - Warren<br />WG:
        Australia - Walgett<br />WL: Australia - Walcha<br />WN: Australia -
        Wellington<br />WR: Australia - Wangaratta<br />WW: Australia - West
        Wyalong<br />X: Australia - Ararat<br />Y: Australia - Albury<br />YA:
        Australia - Yass<br />YM: Australia - Yarram<br />YO: Australia -
        Young<br />Z: Australia - Albany
    CentreCodeBelgium:
      enum:
        - ZB
      type: string
      description: >-
        This is Centres for Belgium. A centre is a town where any activity
        connected with the wool industry takes place. The codes used in
        transmissions are those defined in the Australian Wool Selling
        Regulation.<br />ZB: Brussels - Belgium
    CentreCodeChina:
      enum:
        - ZM
        - ZP
        - ZQ
        - ZR
      type: string
      description: >-
        This is Centres for China. A centre is a town where any activity
        connected with the wool industry takes place. The codes used in
        transmissions are those defined in the Australian Wool Selling
        Regulation.<br />ZM: Nanjing - China<br />ZP: Shanghai - China<br />ZQ:
        Qingdao - China<br />ZR: Zhangjiagang - China
    CentreCodeFrance:
      enum:
        - ZF
      type: string
      description: >-
        This is Centres for France. A centre is a town where any activity
        connected with the wool industry takes place. The codes used in
        transmissions are those defined in the Australian Wool Selling
        Regulation.<br />ZF: Paris - France
    CentreCodeGermany:
      enum:
        - ZG
        - ZH
      type: string
      description: >-
        This is Centres for Germany. A centre is a town where any activity
        connected with the wool industry takes place. The codes used in
        transmissions are those defined in the Australian Wool Selling
        Regulation.<br />ZG: Berlin - Germany<br />ZH: Blumenthal - Germany
    CentreCodeItaly:
      enum:
        - ZI
        - ZJ
        - ZK
      type: string
      description: >-
        This is Centres for Italy. A centre is a town where any activity
        connected with the wool industry takes place. The codes used in
        transmissions are those defined in the Australian Wool Selling
        Regulation.<br />ZI: Rome - Italy<br />ZJ: Biella - Italy<br />ZK:
        Grisignano - Italy
    CentreCodeNetherlands:
      enum:
        - ZN
      type: string
      description: >-
        This is Centres for Netherlands. A centre is a town where any activity
        connected with the wool industry takes place. The codes used in
        transmissions are those defined in the Australian Wool Selling
        Regulation.<br />ZN: Amsterdam - Netherlands
    CentreCodeNewZealand:
      enum:
        - A
        - AW
        - B
        - BL
        - BT
        - C
        - CV
        - D
        - F
        - FA
        - G
        - GD
        - GO
        - HA
        - HS
        - I
        - J
        - K
        - KA
        - KP
        - L
        - LO
        - LU
        - M
        - MA
        - MK
        - MT
        - MU
        - 'N'
        - NE
        - O
        - OH
        - OI
        - OM
        - OT
        - P
        - PT
        - PU
        - R
        - RG
        - RI
        - S
        - SA
        - SH
        - SY
        - T
        - TA
        - TE
        - TH
        - TP
        - U
        - V
        - W
        - WH
        - WI
        - WR
        - WT
        - WU
        - X
        - 'Y'
        - YP
        - Z
        - ZY
      type: string
      description: >-
        This is Centres for New Zealand. A centre is a town where any activity
        connected with the wool industry takes place. The codes used in
        transmissions are those defined in the Australian Wool Selling
        Regulation.<br />A: New Zealand - Auckland<br />AW: New Zealand -
        Awatoto<br />B: New Zealand - Cambridge<br />BL: New Zealand -
        Blenheim<br />BT: New Zealand - Bunnythorpe<br />C: New Zealand -
        Christchurch<br />CV: New Zealand - Clive<br />D: New Zealand -
        Dunedin<br />F: New Zealand - Feilding<br />FA: New Zealand - Fairlie<br
        />G: New Zealand - Gisborne<br />GD: New Zealand - Geraldine<br />GO:
        New Zealand - Gore<br />HA: New Zealand - Hawera<br />HS: New Zealand -
        Hastings<br />I: New Zealand - Invercargill<br />J: New Zealand -
        Tapanui<br />K: New Zealand - Te Kuiti<br />KA: New Zealand -
        Kakariki<br />KP: New Zealand - Kaiapoi<br />L: New Zealand - Mosgiel<br
        />LO: New Zealand - Longburn<br />LU: New Zealand - Lumsden<br />M: New
        Zealand - Masterton<br />MA: New Zealand - Mangatinoka<br />MK: New
        Zealand - Motueka<br />MT: New Zealand - Milton<br />MU: New Zealand -
        Mataura<br />N: New Zealand - Napier<br />NE: New Zealand - Nelson<br
        />O: New Zealand - Oamaru<br />OH: New Zealand - Ohinewai<br />OI: New
        Zealand - Ohai<br />OM: New Zealand - Omakau<br />OT: New Zealand -
        Otorohonga<br />P: New Zealand - Palmerston North<br />PT: New Zealand -
        Pahiatua<br />PU: New Zealand - Putaruru<br />R: New Zealand -
        Rotorua<br />RG: New Zealand - Rangiora<br />RI: New Zealand - Riwaka<br
        />S: New Zealand - Ashburton<br />SA: New Zealand - Saltwater Creek<br
        />SH: New Zealand - Shannon<br />SY: New Zealand - Sydney<br />T: New
        Zealand - Timaru<br />TA: New Zealand - Tapanui<br />TE: New Zealand -
        TeAnau<br />TH: New Zealand - Taihape<br />TP: New Zealand - Te Puke<br
        />U: New Zealand - Taumaruniu<br />V: New Zealand - Dannevirke<br />W:
        New Zealand - Wellington<br />WH: New Zealand - Whakatu<br />WI: New
        Zealand - Whakatu Industrial Park<br />WR: New Zealand - Wairoa<br />WT:
        New Zealand - Winton<br />WU: New Zealand - Waikuku<br />X: New Zealand
        - Wanganui<br />Y: New Zealand - Whangarei<br />YP: New Zealand -
        Waipukurau<br />Z: New Zealand - Taupo<br />ZY: New Zealand - Ashburton
    CentreCodeSouthAfrica:
      enum:
        - ZS
      type: string
      description: >-
        This is Centres for SouthAfrica. A centre is a town where any activity
        connected with the wool industry takes place. The codes used in
        transmissions are those defined in the Australian Wool Selling
        Regulation.<br />ZS: Cape Town - South Africa
    CentreCodeTaiwan:
      enum:
        - ZO
      type: string
      description: >-
        This is Centres for Taiwan. A centre is a town where any activity
        connected with the wool industry takes place. The codes used in
        transmissions are those defined in the Australian Wool Selling
        Regulation.<br />ZO: Keelung - Taiwan
    CentreCodeUnitedKingdomOfGreatBritain:
      enum:
        - ZE
      type: string
      description: >-
        This is Centres for United Kingdom of Great Britain. A centre is a town
        where any activity connected with the wool industry takes place. The
        codes used in transmissions are those defined in the Australian Wool
        Selling Regulation.<br />ZE: London - United Kingdom of Great Britain
    CentreCodeUnitedStatesOfAmerica:
      enum:
        - ZU
      type: string
      description: >-
        This is Centres for USA. A centre is a town where any activity connected
        with the wool industry takes place. The codes used in transmissions are
        those defined in the Australian Wool Selling Regulation.<br />ZU:
        Washington - USA
    Comment:
      required:
        - text
      type: object
      properties:
        text:
          maxLength: 80
          minLength: 0
          type: string
      additionalProperties: false
    CountryCode:
      enum:
        - AU
        - NZ
        - FR
        - ZA
        - BE
        - GB
        - DE
        - IT
        - NL
        - CN
        - TW
        - US
      type: string
      description: >-
        A code for the country in which the transmission was created. Country
        Code using ISO 3166-1 standard<br />AU: Australia<br />NZ: New
        Zealand<br />FR: France<br />ZA: South Africa<br />BE: Belgium<br />GB:
        United Kingdom of Great Britain<br />DE: Germany<br />IT: Italy<br />NL:
        Netherlands<br />CN: China<br />TW: Taiwan<br />US: USA
    CustomProblemDetails:
      required:
        - status
        - title
      type: object
      properties:
        type:
          type: string
          description: "A URI reference [RFC3986] that identifies the problem type.\r\nThis specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]). \r\nWhen this member is not present, its value is assumed to be \"about:blank\".      \r\ne.g. For 400 Bad Request, the \"type\" value can be \"https://tools.ietf.org/html/rfc9110#section-15.5.1\""
          nullable: true
        title:
          minLength: 1
          type: string
          description: "A short, human-readable summary of the problem type. \r\nIt SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4).\r\ne.g. \"One or more validation errors occurred.\""
        status:
          type: integer
          description: >-
            The HTTP status code ([RFC7231], Section 6) generated by the origin
            server for this occurrence of the problem.
          format: int32
        detail:
          type: string
          description: >-
            A human-readable explanation specific to this occurrence of the
            problem. e.g. 400, 403, etc.
          nullable: true
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
            nullable: true
          description: >-
            Dictionary of errors in <PropertyName, ErrorDetails[]> format. e.g.
            errors: { "name": ["Product name is required"], "category":
            ["Category name cannot be longer than 20 characters."]  }
          nullable: true
      additionalProperties: false
      description: >-
        A machine-readable format for specifying errors in HTTP API responses
        based on https://tools.ietf.org/html/rfc7807.
    Organisation:
      required:
        - organisationCode
      type: object
      properties:
        organisationCode:
          maxLength: 3
          minLength: 0
          type: string
        centre:
          $ref: '#/components/schemas/Centre'
      additionalProperties: false
    RequestForTexts:
      required:
        - requestType
      type: object
      properties:
        saleIdentity:
          $ref: '#/components/schemas/SaleIdentity'
        organisationRequested:
          maxLength: 5
          minLength: 0
          type: string
          nullable: true
        saleDateRequested:
          maxLength: 10
          minLength: 0
          pattern: >-
            /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO 8601 standard. e.g. 2024-03-21
          format: date
          nullable: true
        startDateTimeStatusRequest:
          maxLength: 20
          minLength: 0
          pattern: >-
            ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
          type: string
          description: >-
            Date and Time value in ISO 8601 standard UTC format. e.g.
            2024-03-21T19:25:04Z
          format: date-time
          nullable: true
        endDateTimeStatusRequest:
          maxLength: 20
          minLength: 0
          pattern: >-
            ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
          type: string
          description: >-
            Date and Time with offset value in ISO 8601 standard UTC format.
            e.g. 2024-03-21T19:25:04Z
          format: date-time
          nullable: true
        useNetworkDateTime:
          maxLength: 5
          minLength: 0
          type: boolean
          nullable: true
        requestType:
          $ref: '#/components/schemas/RequestTypeForData'
        woolTypeGroup:
          $ref: '#/components/schemas/WoolTypeGroup'
        recordTypesToBeExcluded:
          maxLength: 80
          minLength: 0
          type: array
          items:
            type: string
          description: >-
            Record types and record sub-types to be excluded. e.g. 20 - Lot
            Header, 22A - Group Header
          nullable: true
        season:
          pattern: '-?\d{1,2}'
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    RequestTypeForData:
      enum:
        - 1
        - 3
        - 4
      type: integer
      description: >-
        1: Private Data Request<br />3: Data Re-Request<br />4: Broadcast Data
        Request
      format: int32
    SaleIdentity:
      required:
        - saleNumber
        - sellingCentreType
      type: object
      properties:
        sellingCentreType:
          $ref: '#/components/schemas/SellingCentreType'
        saleNumber:
          maxLength: 2
          minLength: 0
          pattern: '-?\d{1,2}'
          type: integer
          format: int32
      additionalProperties: false
    SellingCentreType:
      enum:
        - NZ_C
        - NZ_N
        - AU_A
        - AU_AU
        - AU_B
        - AU_F
        - AU_G
        - AU_L
        - AU_M
        - AU_N
        - AU_R
        - AU_S
        - PS
        - T
      type: string
      description: >-
        NZ_C: Christchurch<br />NZ_N: Napier<br />AU_A: Adelaide<br />AU_AU:
        Australia<br />AU_B: Brisbane<br />AU_F: Fremantle<br />AU_G: Geelong<br
        />AU_L: Launceston<br />AU_M: Melbourne<br />AU_N: Newcastle<br />AU_R:
        Goulburn<br />AU_S: Sydney<br />PS: Private Sales<br />T: Auctions Plus
        Sales
    SoftwareCompany:
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
      type: integer
      description: >-
        1: Talman<br />2: Symbotic<br />3: Jumbuck/Datacon<br />4: Jemalong<br
        />5: NA - no value<br />6: Modiano<br />7: AWH<br />6: AWTA
      format: int32
    SoftwareIdentifier:
      type: object
      properties:
        softwareCompany:
          $ref: '#/components/schemas/SoftwareCompany'
        version:
          pattern: '-?\d{1,4}'
          type: integer
          description: Version no. e.g. 2400
          format: int32
          nullable: true
        programName:
          maxLength: 4
          minLength: 0
          type: string
          nullable: true
      additionalProperties: false
    Text:
      required:
        - comments
        - transmissionHeader
      type: object
      properties:
        transmissionHeader:
          $ref: '#/components/schemas/TransmissionHeader'
        transferConfig:
          $ref: '#/components/schemas/TransferConfig'
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
      additionalProperties: false
    Texts:
      required:
        - textList
      type: object
      properties:
        textList:
          type: array
          items:
            $ref: '#/components/schemas/Text'
      additionalProperties: false
    TextsApiResult:
      required:
        - isSuccessful
      type: object
      properties:
        isSuccessful:
          type: boolean
          description: Indicator if the request has been successfully processed.
        message:
          type: string
          description: Contains information about the response if applicable.
          nullable: true
        data:
          $ref: '#/components/schemas/Texts'
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    TransferConfig:
      required:
        - transferType
      type: object
      properties:
        transferType:
          $ref: '#/components/schemas/TransferType'
        finalReceiverList:
          type: array
          items:
            $ref: '#/components/schemas/Organisation'
          nullable: true
      additionalProperties: false
    TransferType:
      enum:
        - Unrestrict
        - Restrict
        - Exclude
      type: string
      description: >-
        Unrestrict: Send document to all members<br />Restrict: Send document to
        appointed members<br />Exclude: Send to all members excluding the
        appointed members
    TransmissionHeader:
      required:
        - abn
        - countryOfOrigin
        - currentReceiver
        - dateFormatLastRevised
        - dateTransmissionFileCreated
        - documentOriginator
      type: object
      properties:
        dateFormatLastRevised:
          maxLength: 10
          minLength: 0
          pattern: >-
            /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: >-
            Date value in ISO standard UTC date format. e.g. 2024-03-21
            (YYYY-MM-DD)
          format: date
        dateTransmissionFileCreated:
          maxLength: 10
          minLength: 0
          pattern: >-
            /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: >-
            Date value in ISO standard UTC date format. e.g. 2024-03-21
            (YYYY-MM-DD)
          format: date
        countryOfOrigin:
          $ref: '#/components/schemas/CountryCode'
        documentOriginator:
          $ref: '#/components/schemas/Organisation'
        currentReceiver:
          $ref: '#/components/schemas/Organisation'
        versionNumber:
          pattern: '-?\d{1,2}'
          type: integer
          description: Two digits. e.g. 99
          format: int32
          nullable: true
        softwareIdentifier:
          $ref: '#/components/schemas/SoftwareIdentifier'
        abn:
          maxLength: 11
          minLength: 0
          pattern: ^[0-9]+$
          type: string
          description: Australian Business Number, 11 digits string
      additionalProperties: false
    WoolTypeGroup:
      enum:
        - MFLC
        - MSKT
        - XBFS
        - ODDS
      type: string
      description: >-
        A code to indicate which section of the sale that lot belongs.<br
        />MFLC: Merino fleece types<br />MSKT: Merino fleece types<br />XBFS:
        Merino fleece types<br />ODDS: Merino fleece types
  securitySchemes:
    Bearer:
      type: apiKey
      description: >-
        JWT Access Token that is added in the Authorization header of the HTTP
        request. Example: "Authorization: Bearer {token}". The JWT serves as a
        credential that proves the identity of the client to the server.
      name: Authorization
      in: header
    oauth2:
      type: oauth2
      description: >-
        Authentication for client applications by providing Client ID and Client
        Secret for an JWT Access Token.
      flows:
        clientCredentials:
          tokenUrl: /auth-server/oauth/token
          scopes: {}
security:
  - Bearer: []
