openapi: 3.0.1
info:
  title: WIEDPUG API
  description: API Documentation for the WIEDPUG Network
  termsOfService: https://wiedpug.github.io/wiedpug
  contact:
    name: WIEDPUG Team
    url: https://wiedpug.github.io/wiedpug
    email: changethis@email.com
  license:
    name: Applicable License
    url: https://wiedpug.github.io/wiedpug
  version: v0.0
paths:
  /v0/payment-advice:
    post:
      tags:
        - Payment Advice
      summary: Payment Advice
      description: Used to provide payment advices
      operationId: CreatePaymentAdvices
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentAdvices'
            example:
              paymentAdviceCollection:
                - transmissionHeader:
                    dateFormatLastRevised: '2020-07-15'
                    dateTransmissionFileCreated: '2016-01-17'
                    countryOfOrigin: AU
                    documentOriginator:
                      organisationId: ABCD
                    currentReceiver:
                      organisationId: ATWA
                    versionNumber: 31
                    softwareIdentifier:
                      softwareCompany: 1
                      version: 1082
                      programName: NETR
                    abn: '72001967184'
                  finalreceiverList:
                    - organisationId: ABEF
                    - organisationId: ABFF
                  paymentAdviceDetailList:
                    - woolSaleHeaderLots:
                        season: 16
                        saleIdentity:
                          sellingCentreType: AU_M
                          saleNumber: 29
                        centreStorage: AU_AR
                        saleDate: '2017-01-19'
                        woolState: A
                        packType: '2'
                        invoicingOrganisation:
                          organisationId: ABCD
                        sellingOrganisation:
                          organisationId: ABCD
                        centreCatalogue: AU_G
                        storageOrganisation: ABCD
                        storageDescription: 45 MAIN ST
                        discountRate: 1.5
                        maximumDaysDiscount: 0
                        dateStorageChargeCommences: '2017-01-24'
                        storageChargePerBalePerDay: 0.245
                        penaltyInterestRate: 11.35
                      lotPaymentDetails:
                        - lotIdentity: '123256'
                          lotLastCost: 23.45
                      paymentSummary:
                        lastCostPaid: 67
                        discountAmount: 23
                        netAmountPaid: 77
                        datePaymentMade: '2024-05-24'
                  comments:
                    - text: dfsfbsdfafsafs fdsa
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResult'
              example:
                isSuccessful: true
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred
                status: 400
                detail: ''
                errors:
                  TransmissionHeader.DateFormatLastRevised:
                    - The field DateFormatLastRevised is required
                    - The field DateFormatLastRevised must match regulart expression pattern...
                  TransmissionHeader.CountryOfOrigin:
                    - The field CountryOfOrigin is required
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
  /v0/payment-advice/data:
    post:
      tags:
        - Payment Advice
      summary: Retrieves the payment advices
      operationId: RequestForPaymentAdvices
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestForPaymentAdvice'
            example:
              saleIdentity:
                sellingCentreType: AU_M
                saleNumber: 18
              organisationRequested: AWNF
              saleDateRequested: '2023-10-31'
              useNetworkDateTime: false
              requestType: 4
              woolTypeGroup: MFLC
              season: 23
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentAdvicesApiResult'
              example:
                isSuccessful: true
                data:
                  paymentAdviceCollection:
                    - transmissionHeader:
                        dateFormatLastRevised: '2020-07-15'
                        dateTransmissionFileCreated: '2016-01-17'
                        countryOfOrigin: AU
                        documentOriginator:
                          organisationId: AWTA
                        currentReceiver:
                          organisationId: MNCL
                        versionNumber: 31
                        softwareIdentifier:
                          softwareCompany: 1
                          version: 1082
                          programName: NETR
                        abn: '72001967184'
                      paymentAdviceDetailList:
                        - woolSaleHeaderLots:
                            season: 16
                            saleIdentity:
                              sellingCentreType: AU_M
                              saleNumber: 29
                            centreStorage: AU_AR
                            saleDate: '2017-01-19'
                            woolState: A
                            packType: '2'
                            invoicingOrganisation:
                              organisationId: ABCD
                            sellingOrganisation:
                              organisationId: ABCD
                            centreCatalogue: AU_G
                            storageOrganisation: ABCD
                            storageDescription: 45 MAIN ST
                            discountRate: 1.5
                            maximumDaysDiscount: 0
                            dateStorageChargeCommences: '2017-01-24'
                            storageChargePerBalePerDay: 0.245
                            penaltyInterestRate: 11.35
                          lotPaymentDetails:
                            - lotIdentity: '123256'
                              lotLastCost: 23.45
                          paymentSummary:
                            lastCostPaid: 67
                            discountAmount: 23
                            netAmountPaid: 77
                            datePaymentMade: '2024-05-24'
                      comments:
                        - text: dfsfbsdfafsafs fdsa
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred
                status: 400
                detail: ''
                errors:
                  Requests[0].TransmissionHeader.DateFormatLastRevised:
                    - The field DateFormatLastRevised is required
                    - The field DateFormatLastRevised must match regulart expression pattern...
                  Requests[0].TransmissionHeader.CountryOfOrigin:
                    - The field CountryOfOrigin is required
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: Resource not found
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
components:
  schemas:
    ApiResult:
      required:
        - isSuccessful
      type: object
      properties:
        isSuccessful:
          type: boolean
          description: Indicator if the request has been successfully processed.
        message:
          type: string
          description: Contains information about the response if applicable.
          nullable: true
        data:
          description: Contains response data. e.g. Auction Catalogue
          nullable: true
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    Centre:
      enum:
        - AU_A
        - AU_AD
        - AU_AR
        - AU_AU
        - AU_B
        - AU_BA
        - AU_BK
        - AU_BL
        - AU_BM
        - AU_BO
        - AU_BR
        - AU_BT
        - AU_C
        - AU_CA
        - AU_CB
        - AU_CC
        - AU_CL
        - AU_CN
        - AU_CO
        - AU_CR
        - AU_CU
        - AU_CW
        - AU_D
        - AU_DE
        - AU_DO
        - AU_DR
        - AU_E
        - AU_ER
        - AU_ES
        - AU_F
        - AU_G
        - AU_GF
        - AU_GI
        - AU_GN
        - AU_GR
        - AU_GU
        - AU_H
        - AU_HA
        - AU_HB
        - AU_HM
        - AU_HO
        - AU_HY
        - AU_I
        - AU_J
        - AU_JA
        - AU_K
        - AU_KE
        - AU_KH
        - AU_KI
        - AU_KN
        - AU_KT
        - AU_KW
        - AU_KY
        - AU_L
        - AU_LC
        - AU_M
        - AU_MA
        - AU_MB
        - AU_MC
        - AU_ME
        - AU_MG
        - AU_MI
        - AU_MO
        - AU_MR
        - AU_MU
        - AU_N
        - AU_NA
        - AU_ND
        - AU_NO
        - AU_NR
        - AU_OB
        - AU_OR
        - AU_P
        - AU_PA
        - AU_PL
        - AU_Q
        - AU_QU
        - AU_R
        - AU_S
        - AU_SG
        - AU_SH
        - AU_SK
        - AU_SW
        - AU_SY
        - AU_T
        - AU_TE
        - AU_U
        - AU_UR
        - AU_V
        - AU_W
        - AU_WA
        - AU_WG
        - AU_WL
        - AU_WN
        - AU_WR
        - AU_WW
        - AU_X
        - AU_Y
        - AU_YA
        - AU_YM
        - AU_YO
        - AU_Z
        - OS_ZA
        - OS_ZB
        - OS_ZC
        - OS_ZD
        - OS_ZE
        - OS_ZF
        - OS_ZG
        - OS_ZH
        - OS_ZI
        - OS_ZJ
        - OS_ZK
        - OS_ZL
        - OS_ZM
        - OS_ZN
        - OS_ZO
        - OS_ZP
        - OS_ZQ
        - OS_ZR
        - OS_ZS
        - OS_ZT
        - OS_ZU
        - OS_ZV
        - OS_ZW
        - OS_ZX
        - OS_ZY
        - OS_ZZ
        - NZ_A
        - NZ_AW
        - NZ_B
        - NZ_BL
        - NZ_BT
        - NZ_C
        - NZ_CV
        - NZ_D
        - NZ_F
        - NZ_FA
        - NZ_G
        - NZ_GD
        - NZ_GO
        - NZ_HA
        - NZ_HS
        - NZ_I
        - NZ_J
        - NZ_K
        - NZ_KA
        - NZ_KP
        - NZ_L
        - NZ_LO
        - NZ_LU
        - NZ_M
        - NZ_MA
        - NZ_MK
        - NZ_MT
        - NZ_MU
        - NZ_N
        - NZ_NE
        - NZ_O
        - NZ_OH
        - NZ_OI
        - NZ_OM
        - NZ_OT
        - NZ_P
        - NZ_PT
        - NZ_PU
        - NZ_R
        - NZ_RG
        - NZ_RI
        - NZ_S
        - NZ_SA
        - NZ_SH
        - NZ_SY
        - NZ_T
        - NZ_TA
        - NZ_TE
        - NZ_TH
        - NZ_TP
        - NZ_U
        - NZ_V
        - NZ_W
        - NZ_WH
        - NZ_WI
        - NZ_WR
        - NZ_WT
        - NZ_WU
        - NZ_X
        - NZ_Y
        - NZ_YP
        - NZ_Z
      type: string
      description: ''
    ChargeType:
      enum:
        - PenaltyInterest
        - MiscellaneousAdjustments
      type: string
    Comment:
      required:
        - text
      type: object
      properties:
        text:
          maxLength: 80
          minLength: 0
          type: string
      additionalProperties: false
    CountryCode:
      enum:
        - AU
        - NZ
        - FR
        - ZA
      type: string
      description: 'A code for the country in which the transmission was created. Country Code using ISO 3166-1 standard<br />AU: Australia<br />NZ: New Zealand<br />FR: France<br />ZA: South Africa'
    Currency:
      enum:
        - AED
        - CAD
        - CHF
        - CZK
        - DKK
        - EUR
        - GBP
        - HKD
        - HUF
        - ILS
        - JPY
        - NOK
        - NZD
        - SEK
        - SGD
        - THB
        - USD
        - ZAR
      type: string
      description: 'AED: United Arab Emirates Dirham<br />CAD: Canadian Dollar<br />CHF: Swiss Franc<br />CZK: Czech Koruna<br />DKK: Danish Kroner<br />EUR: Euro<br />GBP: Great British Pound<br />HKD: Hong Kong Dollar<br />HUF: Hungarian Forint<br />ILS: Israeli New Shekel<br />JPY: Japanese Yen<br />NOK: Norwegian Kroner<br />NZD: New Zealand Dollar<br />SEK: Swedish Kronor<br />SGD: Singapore Dollar<br />THB: Thailand Baht<br />USD: United States Dollar<br />ZAR: South African Rand'
    CustomProblemDetails:
      required:
        - status
        - title
      type: object
      properties:
        type:
          type: string
          description: "A URI reference [RFC3986] that identifies the problem type.\r\nThis specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]). \r\nWhen this member is not present, its value is assumed to be \"about:blank\".      \r\ne.g. For 400 Bad Request, the \"type\" value can be \"https://tools.ietf.org/html/rfc9110#section-15.5.1\""
          nullable: true
        title:
          minLength: 1
          type: string
          description: "A short, human-readable summary of the problem type. \r\nIt SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4).\r\ne.g. \"One or more validation errors occurred.\""
        status:
          type: integer
          description: The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
          format: int32
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem. e.g. 400, 403, etc.
          nullable: true
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
            nullable: true
          description: 'Dictionary of errors in <PropertyName, ErrorDetails[]> format. e.g. errors: { "name": ["Product name is required"], "category": ["Category name cannot be longer than 20 characters."]  }'
          nullable: true
      additionalProperties: false
      description: A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.
    DebitCreditFlag:
      enum:
        - 1
        - 2
      type: integer
      description: '1: Debit<br />2: Credit'
      format: int32
    LotPaymentDetail:
      required:
        - lotIdentity
        - lotLastCost
      type: object
      properties:
        lotIdentity:
          minLength: 1
          pattern: '-?\d{1,6}'
          type: string
          description: Required alphanumeric field for the first lot identity.
        lotLastCost:
          pattern: ^-?\d{1,12}\.\d{2}$
          type: number
          description: Required decimal field for the last cost of the first lot with two digits precision.
          format: double
      additionalProperties: false
    MiscellaneousCharge:
      required:
        - chargeAmount
        - currency
        - debitCreditFlag
      type: object
      properties:
        chargeType:
          $ref: '#/components/schemas/ChargeType'
        chargeDescription:
          maxLength: 40
          minLength: 0
          type: string
          description: Optional alphanumeric field for charge description.
          nullable: true
        currency:
          $ref: '#/components/schemas/Currency'
        chargeAmount:
          pattern: ^-?\d{1,12}\.\d{2}$
          type: number
          description: Required decimal field for charge amount with two digits precision.
          format: double
        debitCreditFlag:
          $ref: '#/components/schemas/DebitCreditFlag'
      additionalProperties: false
    Organisation:
      type: object
      properties:
        organisationCodeAndCentre:
          $ref: '#/components/schemas/OrganisationCodeAndCentre'
        organisationId:
          maxLength: 5
          minLength: 0
          type: string
          nullable: true
      additionalProperties: false
    OrganisationCodeAndCentre:
      required:
        - centre
        - organisationCode
      type: object
      properties:
        organisationCode:
          maxLength: 3
          minLength: 0
          type: string
        centre:
          $ref: '#/components/schemas/Centre'
      additionalProperties: false
    PackType:
      enum:
        - '0'
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        - '7'
        - '8'
        - '9'
        - A
        - B
        - C
        - D
        - E
        - F
        - Z
      type: string
      description: 'A code used to indicate how the wool has been baled. The most common type is Farm bales. <strong>Original</strong> - the pack type when the wool was originally baled. <strong>Preferred</strong> - The pack type which the buyer would prefer to be used when his wool is dumped.<br />0: Standard (farm) bale<br />1: Bag/butt<br />2: Lightweight bale<br />3: Jumbo bale<br />4: Single bales (normal density dumped)<br />5: Single bales (high density dumped)<br />6: Single bales (super high density dumped)<br />7: 3 bale tripack (super high density dumped)<br />8: 2 bale tripack (super high density dumped)<br />9: U bales<br />A: 4 or 6 bale unitised (normal density dumped)<br />B: 4 or 6 bale unitised (high density dumped)<br />C: 4 or 6 bale unitised (super high density dumped)<br />D: Two Bale Module (2BM)<br />E: J9 size bale used for scoured wool<br />F: J12 size bale used for scoured wool<br />Z: Mixed (to be used with groups only, that is, record type 12)'
    PaymentAdvice:
      required:
        - paymentAdviceDetailList
        - transmissionHeader
      type: object
      properties:
        transmissionHeader:
          $ref: '#/components/schemas/TransmissionHeader'
        finalreceiverList:
          type: array
          items:
            $ref: '#/components/schemas/Organisation'
          nullable: true
        paymentAdviceDetailList:
          type: array
          items:
            $ref: '#/components/schemas/PaymentAdviceDetail'
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
          nullable: true
      additionalProperties: false
    PaymentAdviceDetail:
      required:
        - lotPaymentDetails
        - paymentSummary
        - woolSaleHeaderLots
      type: object
      properties:
        woolSaleHeaderLots:
          $ref: '#/components/schemas/PaymentAdviceWoolSaleHeaderLots'
        lotPaymentDetails:
          type: array
          items:
            $ref: '#/components/schemas/LotPaymentDetail'
        miscellaneousCharges:
          type: array
          items:
            $ref: '#/components/schemas/MiscellaneousCharge'
          nullable: true
        paymentSummary:
          $ref: '#/components/schemas/PaymentSummary'
      additionalProperties: false
    PaymentAdviceWoolSaleHeaderLots:
      required:
        - centreCatalogue
        - centreStorage
        - dateStorageChargeCommences
        - discountRate
        - invoicingOrganisation
        - maximumDaysDiscount
        - packType
        - penaltyInterestRate
        - saleDate
        - saleIdentity
        - season
        - sellingOrganisation
        - storageChargePerBalePerDay
        - storageOrganisation
        - woolState
      type: object
      properties:
        season:
          pattern: '-?\d{1,2}'
          type: integer
          description: Two digits e.g. 99
          format: int32
        saleIdentity:
          $ref: '#/components/schemas/SaleIdentity'
        centreStorage:
          $ref: '#/components/schemas/Centre'
        saleDate:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD)
          format: date
        woolState:
          $ref: '#/components/schemas/WoolState'
        packType:
          $ref: '#/components/schemas/PackType'
        invoicingOrganisation:
          $ref: '#/components/schemas/Organisation'
        sellingOrganisation:
          $ref: '#/components/schemas/Organisation'
        centreCatalogue:
          $ref: '#/components/schemas/Centre'
        storageOrganisation:
          maxLength: 5
          minLength: 0
          type: string
          description: "This is the organisation store that is storing the wool. \r\nNote: If there is more than one organisation in a centre, then separate AWEX codes are required for each store.\r\nIt is not necessarily the same as the Releasing Organisation."
        storageDescription:
          maxLength: 15
          minLength: 0
          type: string
          description: Used to provide more details on location within the Storage Organisations facility - such as street address, warehouse number etc. – to assist delivery.
          nullable: true
        discountRate:
          pattern: ^-?\d{1,2}\.\d{2}$
          type: number
          description: Total 4 digits with 2 digits after the decimal point. e.g. 23.76
          format: double
        maximumDaysDiscount:
          pattern: '-?\d{1,2}'
          type: integer
          description: 2 digits number. e.g. 23
          format: int32
        dateStorageChargeCommences:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO 8601 standard UTC date format. e.g. 2024-03-21
          format: date
        storageChargePerBalePerDay:
          pattern: ^-?\d{1}\.\d{3}$
          type: number
          description: Total 4 digits with 3 digits after the decimal point. e.g. 23.76
          format: double
        penaltyInterestRate:
          pattern: ^-?\d{1,2}\.\d{2}$
          type: number
          description: Total 4 digits with 2 digits after the decimal point. e.g. 23.76
          format: double
        lotAvailableDate:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: "The first date on which the wool is available for purchase.\r\nDate value in ISO 8601 standard UTC date format. e.g. 2024-03-21."
          format: date
          nullable: true
        postSaleChargeRebate:
          pattern: ^-?\d{1,3}\.\d{2}$
          type: number
          description: "The total (extended) amount of Post Sale Charge Rebate for the Lot. \r\nThis value is provided where a value in the Post Sale Charge Rebate field exists (11A)\r\nTotal 5 digits with 2 digits after the decimal point. e.g. 123.76"
          format: double
          nullable: true
      additionalProperties: false
    PaymentAdvices:
      required:
        - paymentAdviceCollection
      type: object
      properties:
        paymentAdviceCollection:
          type: array
          items:
            $ref: '#/components/schemas/PaymentAdvice'
      additionalProperties: false
    PaymentAdvicesApiResult:
      required:
        - isSuccessful
      type: object
      properties:
        isSuccessful:
          type: boolean
          description: Indicator if the request has been successfully processed.
        message:
          type: string
          description: Contains information about the response if applicable.
          nullable: true
        data:
          $ref: '#/components/schemas/PaymentAdvices'
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    PaymentSummary:
      required:
        - datePaymentMade
        - discountAmount
        - lastCostPaid
        - netAmountPaid
      type: object
      properties:
        lastCostPaid:
          pattern: /^\d+(\.\d{2})?$/
          type: number
          description: Required decimal field for the last cost paid with two digits precision.
          format: double
        discountAmount:
          pattern: /^\d+(\.\d{2})?$/
          type: number
          description: Required decimal field for discount amount with two digits precision.
          format: double
        netAmountPaid:
          pattern: /^\d+(\.\d{2})?$/
          type: number
          description: Required decimal field for net amount paid with two digits precision.
          format: double
        datePaymentMade:
          minLength: 1
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Required date field for the date payment was made.
          format: date
      additionalProperties: false
    RequestForPaymentAdvice:
      required:
        - requestType
      type: object
      properties:
        saleIdentity:
          $ref: '#/components/schemas/SaleIdentity'
        organisationRequested:
          maxLength: 5
          minLength: 0
          type: string
          nullable: true
        saleDateRequested:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO 8601 standard. e.g. 2024-03-21
          format: date
          nullable: true
        startDateTimeStatusRequest:
          maxLength: 20
          minLength: 0
          pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
          type: string
          description: Date and Time value in ISO 8601 standard UTC format. e.g. 2024-03-21T19:25:04Z
          format: date-time
          nullable: true
        endDateTimeStatusRequest:
          maxLength: 20
          minLength: 0
          pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
          type: string
          description: Date and Time with offset value in ISO 8601 standard UTC format. e.g. 2024-03-21T19:25:04Z
          format: date-time
          nullable: true
        useNetworkDateTime:
          maxLength: 5
          minLength: 0
          type: boolean
          nullable: true
        requestType:
          $ref: '#/components/schemas/RequestTypeForData'
        woolTypeGroup:
          $ref: '#/components/schemas/WoolTypeGroup'
        recordTypesToBeExcluded:
          maxLength: 80
          minLength: 0
          type: array
          items:
            type: string
          description: Record types and record sub-types to be excluded. e.g. 20 - Lot Header, 22A - Group Header
          nullable: true
        season:
          pattern: '-?\d{1,2}'
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    RequestTypeForData:
      enum:
        - 1
        - 3
        - 4
      type: integer
      description: '1: Private Data Request<br />3: Data Re-Request<br />4: Broadcast Data Request'
      format: int32
    SaleIdentity:
      required:
        - saleNumber
        - sellingCentreType
      type: object
      properties:
        sellingCentreType:
          $ref: '#/components/schemas/SellingCentreType'
        saleNumber:
          maxLength: 2
          minLength: 0
          pattern: '-?\d{1,2}'
          type: integer
          format: int32
      additionalProperties: false
    SellingCentreType:
      enum:
        - NZ_C
        - NZ_N
        - AU_A
        - AU_AU
        - AU_B
        - AU_F
        - AU_G
        - AU_L
        - AU_M
        - AU_N
        - AU_R
        - AU_S
        - PS
        - T
      type: string
      description: 'NZ_C: Christchurch<br />NZ_N: Napier<br />AU_A: Adelaide<br />AU_AU: Australia<br />AU_B: Brisbane<br />AU_F: Fremantle<br />AU_G: Geelong<br />AU_L: Launceston<br />AU_M: Melbourne<br />AU_N: Newcastle<br />AU_R: Goulburn<br />AU_S: Sydney<br />PS: Private Sales<br />T: Auctions Plus Sales'
    SoftwareCompany:
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
      type: integer
      description: '1: Talman<br />2: Symbotic<br />3: Jumbuck/Datacon<br />4: Jemalong<br />5: NA - no value<br />6: Modiano<br />7: AWH<br />6: AWTA'
      format: int32
    SoftwareIdentifier:
      type: object
      properties:
        softwareCompany:
          $ref: '#/components/schemas/SoftwareCompany'
        version:
          pattern: '-?\d{1,4}'
          type: integer
          description: Version no. e.g. 2400
          format: int32
          nullable: true
        programName:
          maxLength: 4
          minLength: 0
          type: string
          nullable: true
      additionalProperties: false
    TransmissionHeader:
      required:
        - abn
        - countryOfOrigin
        - currentReceiver
        - dateFormatLastRevised
        - dateTransmissionFileCreated
        - documentOriginator
      type: object
      properties:
        dateFormatLastRevised:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD)
          format: date
        dateTransmissionFileCreated:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD)
          format: date
        countryOfOrigin:
          $ref: '#/components/schemas/CountryCode'
        documentOriginator:
          $ref: '#/components/schemas/Organisation'
        currentReceiver:
          $ref: '#/components/schemas/Organisation'
        versionNumber:
          pattern: '-?\d{1,2}'
          type: integer
          description: Two digits. e.g. 99
          format: int32
          nullable: true
        softwareIdentifier:
          $ref: '#/components/schemas/SoftwareIdentifier'
        abn:
          maxLength: 11
          minLength: 0
          pattern: ^[0-9]+$
          type: string
          description: Australian Business Number, 11 digits string
      additionalProperties: false
    WoolState:
      enum:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '6'
        - '7'
        - '8'
        - '9'
        - A
        - C
        - M
      type: string
      description: The state of the wool itemised in the invoice.<br />1. Greasy<br />2. Dead<br />3. Slipe<br />4. Scoured<br />5. Carbonised<br />6. Wool tops<br />7. Wool noils<br />8. Carded sliver<br />9. Other processed wool<br />A. Alpaca<br />C. Cashmere<br />M. Mohair
    WoolTypeGroup:
      enum:
        - MFLC
        - MSKT
        - XBFS
        - ODDS
      type: string
      description: 'A code to indicate which section of the sale that lot belongs.<br />MFLC: Merino fleece types<br />MSKT: Merino fleece types<br />XBFS: Merino fleece types<br />ODDS: Merino fleece types'
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Access Token that is added in the Authorization header of the HTTP request. Example: "Authorization: Bearer {token}". The JWT serves as a credential that proves the identity of the client to the server.'
      name: Authorization
      in: header
    oauth2:
      type: oauth2
      description: Authentication for client applications by providing Client ID and Client Secret for an JWT Access Token.
      flows:
        clientCredentials:
          tokenUrl: /auth-server/oauth/token
          scopes: {}
security:
  - Bearer: []
