openapi: 3.0.1
info:
  title: WIEDPUG API
  description: API Documentation for the WIEDPUG Network
  termsOfService: https://wiedpug.github.io/wiedpug
  contact:
    name: WIEDPUG Team
    url: https://wiedpug.github.io/wiedpug
    email: changethis@email.com
  license:
    name: Applicable License
    url: https://wiedpug.github.io/wiedpug
  version: v0.0
paths:
  /v0/postsale-printing-of-presale-certificates:
    post:
      tags:
        - Request Postsale Printing Of Presale Certificates
      summary: Request Postsale Printing Of Presale Certificates
      description: Used to provide request postsale printing of presale certificates
      operationId: CreateRequestPostsalePrintingOfPresaleCertificates
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestPostsalePrintingOfPresaleCertificates'
            example:
              transmissionHeader:
                dateFormatLastRevised: '2020-07-15'
                dateTransmissionFileCreated: '2016-01-17'
                countryOfOrigin: AU
                documentOriginator:
                  organisationId: ABCD
                currentReceiver:
                  organisationId: ATWA
                versionNumber: 31
                softwareIdentifier:
                  softwareCompany: 1
                  version: 1082
                  programName: NETR
                abn: '72001967184'
              confirmations:
                - paymentHeader:
                    clientCode:
                      organisationId: AWCED
                    statementDate: '2024-05-11'
                    amountEmitted: 0
                    statementPaymentDate: '2024-06-01'
                    bankBSBNumber: '335567'
                    bankAccountNumber: '456735'
                    amountWithheldThisStatement: 690.45
                    amountWithheldPreviousStatements: 672.23
                  paymentDetails:
                    - statementDate: '2024-05-12'
                      accountReference: '12345678901'
                      amount: 723.23
                      paymentType: 0
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResult'
              example:
                isSuccessful: true
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred
                status: 400
                detail: ''
                errors:
                  TransmissionHeader.DateFormatLastRevised:
                    - The field DateFormatLastRevised is required
                    - The field DateFormatLastRevised must match regulart expression pattern...
                  TransmissionHeader.CountryOfOrigin:
                    - The field CountryOfOrigin is required
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
  /v0/postsale-printing-of-presale-certificates/data:
    post:
      tags:
        - Request Postsale Printing Of Presale Certificates
      summary: Retrieves the request postsale printing of presale certificates
      operationId: RequestForRequestPostsalePrintingOfPresaleCertificates
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestForRequestPostsalePrintingOfPresaleCertificates'
            example:
              saleIdentity:
                sellingCentreType: AU_M
                saleNumber: 18
              organisationRequested: AWNF
              saleDateRequested: '2023-10-31'
              useNetworkDateTime: false
              requestType: 4
              woolTypeGroup: MFLC
              season: 23
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestPostsalePrintingOfPresaleCertificatesApiResult'
              example:
                isSuccessful: true
                data:
                  transmissionHeader:
                    dateFormatLastRevised: '2020-07-15'
                    dateTransmissionFileCreated: '2016-01-17'
                    countryOfOrigin: AU
                    documentOriginator:
                      organisationId: AWTA
                    currentReceiver:
                      organisationId: ATWA
                    versionNumber: 31
                    softwareIdentifier:
                      softwareCompany: 1
                      version: 1082
                      programName: NETR
                    abn: '72001967184'
                  printPreSaleCertificatePostSales:
                    - certificateIdentity:
                        certificateIDPrefix: 2
                        certificateIDSuffix: F
                        certificateIDNumber: '234567'
                        certificateIDCD: 6
                      weightNote:
                        prefix: L
                        suffix: '1234567'
                      lotIdentity: 45567L
                      buyingOrganisation:
                        organisationId: ATWM
                      saleOutcome: 6
                      bales: 23
                      gross: 2340
                      saleIdentity:
                        sellingCentreType: AU_AU
                        saleNumber: 23
                      centreStorage: AU_AR
                      certificateDeliveryIndicator: 0
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.1
                title: One or more validation errors occurred
                status: 400
                detail: ''
                errors:
                  Requests[0].TransmissionHeader.DateFormatLastRevised:
                    - The field DateFormatLastRevised is required
                    - The field DateFormatLastRevised must match regulart expression pattern...
                  Requests[0].TransmissionHeader.CountryOfOrigin:
                    - The field CountryOfOrigin is required
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                detail: Missing authentication credentials
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: You don't have permission to access this resource
                status: 403
                detail: You don't have a 'read' access to access this resource
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#section-15.5.4
                title: Resource not found
                status: 404
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/CustomProblemDetails'
              example:
                type: https://datatracker.ietf.org/doc/html/rfc9110#name-500-internal-server-error
                title: An error occurred while processing your required
                status: 500
                detail: Error details..
components:
  schemas:
    ApiResult:
      required:
        - isSuccessful
      type: object
      properties:
        isSuccessful:
          type: boolean
          description: Indicator if the request has been successfully processed.
        message:
          type: string
          description: Contains information about the response if applicable.
          nullable: true
        data:
          description: Contains response data. e.g. Auction Catalogue
          nullable: true
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    Centre:
      enum:
        - AU_A
        - AU_AD
        - AU_AR
        - AU_AU
        - AU_B
        - AU_BA
        - AU_BK
        - AU_BL
        - AU_BM
        - AU_BO
        - AU_BR
        - AU_BT
        - AU_C
        - AU_CA
        - AU_CB
        - AU_CC
        - AU_CL
        - AU_CN
        - AU_CO
        - AU_CR
        - AU_CU
        - AU_CW
        - AU_D
        - AU_DE
        - AU_DO
        - AU_DR
        - AU_E
        - AU_ER
        - AU_ES
        - AU_F
        - AU_G
        - AU_GF
        - AU_GI
        - AU_GN
        - AU_GR
        - AU_GU
        - AU_H
        - AU_HA
        - AU_HB
        - AU_HM
        - AU_HO
        - AU_HY
        - AU_I
        - AU_J
        - AU_JA
        - AU_K
        - AU_KE
        - AU_KH
        - AU_KI
        - AU_KN
        - AU_KT
        - AU_KW
        - AU_KY
        - AU_L
        - AU_LC
        - AU_M
        - AU_MA
        - AU_MB
        - AU_MC
        - AU_ME
        - AU_MG
        - AU_MI
        - AU_MO
        - AU_MR
        - AU_MU
        - AU_N
        - AU_NA
        - AU_ND
        - AU_NO
        - AU_NR
        - AU_OB
        - AU_OR
        - AU_P
        - AU_PA
        - AU_PL
        - AU_Q
        - AU_QU
        - AU_R
        - AU_S
        - AU_SG
        - AU_SH
        - AU_SK
        - AU_SW
        - AU_SY
        - AU_T
        - AU_TE
        - AU_U
        - AU_UR
        - AU_V
        - AU_W
        - AU_WA
        - AU_WG
        - AU_WL
        - AU_WN
        - AU_WR
        - AU_WW
        - AU_X
        - AU_Y
        - AU_YA
        - AU_YM
        - AU_YO
        - AU_Z
        - OS_ZA
        - OS_ZB
        - OS_ZC
        - OS_ZD
        - OS_ZE
        - OS_ZF
        - OS_ZG
        - OS_ZH
        - OS_ZI
        - OS_ZJ
        - OS_ZK
        - OS_ZL
        - OS_ZM
        - OS_ZN
        - OS_ZO
        - OS_ZP
        - OS_ZQ
        - OS_ZR
        - OS_ZS
        - OS_ZT
        - OS_ZU
        - OS_ZV
        - OS_ZW
        - OS_ZX
        - OS_ZY
        - OS_ZZ
        - NZ_A
        - NZ_AW
        - NZ_B
        - NZ_BL
        - NZ_BT
        - NZ_C
        - NZ_CV
        - NZ_D
        - NZ_F
        - NZ_FA
        - NZ_G
        - NZ_GD
        - NZ_GO
        - NZ_HA
        - NZ_HS
        - NZ_I
        - NZ_J
        - NZ_K
        - NZ_KA
        - NZ_KP
        - NZ_L
        - NZ_LO
        - NZ_LU
        - NZ_M
        - NZ_MA
        - NZ_MK
        - NZ_MT
        - NZ_MU
        - NZ_N
        - NZ_NE
        - NZ_O
        - NZ_OH
        - NZ_OI
        - NZ_OM
        - NZ_OT
        - NZ_P
        - NZ_PT
        - NZ_PU
        - NZ_R
        - NZ_RG
        - NZ_RI
        - NZ_S
        - NZ_SA
        - NZ_SH
        - NZ_SY
        - NZ_T
        - NZ_TA
        - NZ_TE
        - NZ_TH
        - NZ_TP
        - NZ_U
        - NZ_V
        - NZ_W
        - NZ_WH
        - NZ_WI
        - NZ_WR
        - NZ_WT
        - NZ_WU
        - NZ_X
        - NZ_Y
        - NZ_YP
        - NZ_Z
      type: string
      description: ''
    CertificateDeliveryIndicator:
      enum:
        - 0
        - 1
      type: integer
      description: '0: Deliver to Broker/Buyer Address<br />1: Deliver to Clearing House'
      format: int32
    CertificateIDPrefix:
      enum:
        - 2
        - 3
        - 6
      type: integer
      description: '2: Sydney Laboratory<br />3: Melbourne Laboratory<br />6: Fremantle Laboratory'
      format: int32
    CertificateIDSuffix:
      enum:
        - B
        - C
        - D
        - F
        - I
        - J
        - L
        - M
        - 'N'
        - Q
        - P
        - R
        - W
        - 'Y'
      type: string
      description: 'B: Bulk Class<br />C: Colour<br />D: PTC (Pre-Sale Test Certificate – Other Grower Lot)<br />F: Premium Test<br />I: Subjectively Appraised Interlot<br />J: Combination - Yield & Micron, Length & Strength, Colour<br />L: Length & Strength<br />M: Objectively Matched Lot<br />N: Objectively matched Interlot<br />Q: Bulk Class – Quality Managed<br />P: PTC (Pre-sale Test Certificate - Classed Grower Lot)<br />R: Guidance Report<br />W: Scoured Wool<br />Y: Post sale Core Test'
    CertificateIdentity:
      required:
        - certificateIDCD
        - certificateIDNumber
        - certificateIDPrefix
        - certificateIDSuffix
      type: object
      properties:
        certificateIDPrefix:
          $ref: '#/components/schemas/CertificateIDPrefix'
        certificateIDSuffix:
          $ref: '#/components/schemas/CertificateIDSuffix'
        certificateIDNumber:
          maxLength: 8
          minLength: 0
          type: string
        certificateIDCD:
          maxLength: 1
          minLength: 0
          type: integer
          format: int32
      additionalProperties: false
    CountryCode:
      enum:
        - AU
        - NZ
        - FR
        - ZA
      type: string
      description: 'A code for the country in which the transmission was created. Country Code using ISO 3166-1 standard<br />AU: Australia<br />NZ: New Zealand<br />FR: France<br />ZA: South Africa'
    CustomProblemDetails:
      required:
        - status
        - title
      type: object
      properties:
        type:
          type: string
          description: "A URI reference [RFC3986] that identifies the problem type.\r\nThis specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]). \r\nWhen this member is not present, its value is assumed to be \"about:blank\".      \r\ne.g. For 400 Bad Request, the \"type\" value can be \"https://tools.ietf.org/html/rfc9110#section-15.5.1\""
          nullable: true
        title:
          minLength: 1
          type: string
          description: "A short, human-readable summary of the problem type. \r\nIt SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4).\r\ne.g. \"One or more validation errors occurred.\""
        status:
          type: integer
          description: The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
          format: int32
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem. e.g. 400, 403, etc.
          nullable: true
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
            nullable: true
          description: 'Dictionary of errors in <PropertyName, ErrorDetails[]> format. e.g. errors: { "name": ["Product name is required"], "category": ["Category name cannot be longer than 20 characters."]  }'
          nullable: true
      additionalProperties: false
      description: A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.
    Organisation:
      type: object
      properties:
        organisationCodeAndCentre:
          $ref: '#/components/schemas/OrganisationCodeAndCentre'
        organisationId:
          maxLength: 5
          minLength: 0
          type: string
          nullable: true
      additionalProperties: false
    OrganisationCodeAndCentre:
      required:
        - centre
        - organisationCode
      type: object
      properties:
        organisationCode:
          maxLength: 3
          minLength: 0
          type: string
        centre:
          $ref: '#/components/schemas/Centre'
      additionalProperties: false
    PrintFlag:
      enum:
        - Normal
        - A
        - S
        - C
        - E
        - M
        - 'N'
      type: string
      description: 'P: Normal RPP/TCR request to pdf Certificate<br />A: Pdf Combination/OML Certificate and associated sub-lots<br />S: Pdf associated sub-lots excluding the Combination/OML Certificate<br />C: Pdf Combination Certificate in Chinese and English<br />E: Pdf Combination Certificate in Chinese and English & associated sublots in English)<br />M: Pdf Combination Certificate in English & Mulesing Status report<br />N: Pdf Mulesing Status report only'
    PrintPreSaleCertificatePostSale:
      required:
        - bales
        - buyingOrganisation
        - centreStorage
        - certificateDeliveryIndicator
        - certificateIdentity
        - gross
        - lotIdentity
        - saleIdentity
        - saleOutcome
        - weightNote
      type: object
      properties:
        certificateIdentity:
          $ref: '#/components/schemas/CertificateIdentity'
        weightNote:
          $ref: '#/components/schemas/WeightNote'
        lotIdentity:
          maxLength: 6
          minLength: 0
          type: string
          description: Required alphanumeric field for lot identity.
        buyingOrganisation:
          $ref: '#/components/schemas/Organisation'
        saleOutcome:
          $ref: '#/components/schemas/SaleOutcome'
        bales:
          maxLength: 3
          minLength: 0
          pattern: '-?\d{1,3}'
          type: integer
          description: Required numeric field for bales.
          format: int32
        gross:
          maxLength: 5
          minLength: 0
          pattern: '-?\d{1,5}'
          type: integer
          description: Required numeric field for gross weight.
          format: int32
        saleIdentity:
          $ref: '#/components/schemas/SaleIdentity'
        centreStorage:
          $ref: '#/components/schemas/Centre'
        certificateDeliveryIndicator:
          $ref: '#/components/schemas/CertificateDeliveryIndicator'
        costPerWeightUnit:
          maxLength: 6
          minLength: 0
          pattern: '-?\d{1,6}'
          type: integer
          description: Optional numeric field for cost per weight unit.
          format: int32
          nullable: true
        printFlag:
          $ref: '#/components/schemas/PrintFlag'
        printTEAM3HauteurOnCertificate:
          maxLength: 5
          minLength: 0
          type: boolean
          description: "Bool value for TEAM-3 Hauteur - Print.\r\nTrue: Print TEAM-3 Hauteur on Certificate\r\nFalse: Not print TEAM-3 Hauteur on Certificate"
          nullable: true
        woolinkSaleSystem:
          $ref: '#/components/schemas/WoolinkSaleSystem'
        saleType:
          $ref: '#/components/schemas/SaleType'
      additionalProperties: false
    RequestForRequestPostsalePrintingOfPresaleCertificates:
      required:
        - requestType
      type: object
      properties:
        saleIdentity:
          $ref: '#/components/schemas/SaleIdentity'
        organisationRequested:
          maxLength: 5
          minLength: 0
          type: string
          nullable: true
        saleDateRequested:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO 8601 standard. e.g. 2024-03-21
          format: date
          nullable: true
        startDateTimeStatusRequest:
          maxLength: 20
          minLength: 0
          pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
          type: string
          description: Date and Time value in ISO 8601 standard UTC format. e.g. 2024-03-21T19:25:04Z
          format: date-time
          nullable: true
        endDateTimeStatusRequest:
          maxLength: 20
          minLength: 0
          pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
          type: string
          description: Date and Time with offset value in ISO 8601 standard UTC format. e.g. 2024-03-21T19:25:04Z
          format: date-time
          nullable: true
        useNetworkDateTime:
          maxLength: 5
          minLength: 0
          type: boolean
          nullable: true
        requestType:
          $ref: '#/components/schemas/RequestTypeForData'
        woolTypeGroup:
          $ref: '#/components/schemas/WoolTypeGroup'
        recordTypesToBeExcluded:
          maxLength: 80
          minLength: 0
          type: array
          items:
            type: string
          description: Record types and record sub-types to be excluded. e.g. 20 - Lot Header, 22A - Group Header
          nullable: true
        season:
          pattern: '-?\d{1,2}'
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    RequestPostsalePrintingOfPresaleCertificates:
      required:
        - printPreSaleCertificatePostSales
        - transmissionHeader
      type: object
      properties:
        transmissionHeader:
          $ref: '#/components/schemas/TransmissionHeader'
        printPreSaleCertificatePostSales:
          type: array
          items:
            $ref: '#/components/schemas/PrintPreSaleCertificatePostSale'
      additionalProperties: false
    RequestPostsalePrintingOfPresaleCertificatesApiResult:
      required:
        - isSuccessful
      type: object
      properties:
        isSuccessful:
          type: boolean
          description: Indicator if the request has been successfully processed.
        message:
          type: string
          description: Contains information about the response if applicable.
          nullable: true
        data:
          $ref: '#/components/schemas/RequestPostsalePrintingOfPresaleCertificates'
      additionalProperties: false
      description: A standard API response object used for all successful API responses
    RequestTypeForData:
      enum:
        - 1
        - 3
        - 4
      type: integer
      description: '1: Private Data Request<br />3: Data Re-Request<br />4: Broadcast Data Request'
      format: int32
    SaleIdentity:
      required:
        - saleNumber
        - sellingCentreType
      type: object
      properties:
        sellingCentreType:
          $ref: '#/components/schemas/SellingCentreType'
        saleNumber:
          maxLength: 2
          minLength: 0
          pattern: '-?\d{1,2}'
          type: integer
          format: int32
      additionalProperties: false
    SaleOutcome:
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 7
      type: integer
      description: '0: Sold<br />1: Passed In<br />2: Lot withdrawn from sale<br />3: No bid<br />4: Transfer<br />6: Bid or Offer Price<br />7: Withdrawn – Sold Prior'
      format: int32
    SaleType:
      enum:
        - A
        - T
        - O
        - AV
        - E
      type: string
      description: 'A: Auction (open cry)<br />T: Tender<br />O: Offer<br />AV: Availability<br />E: Electronic Sale'
    SellingCentreType:
      enum:
        - NZ_C
        - NZ_N
        - AU_A
        - AU_AU
        - AU_B
        - AU_F
        - AU_G
        - AU_L
        - AU_M
        - AU_N
        - AU_R
        - AU_S
        - PS
        - T
      type: string
      description: 'NZ_C: Christchurch<br />NZ_N: Napier<br />AU_A: Adelaide<br />AU_AU: Australia<br />AU_B: Brisbane<br />AU_F: Fremantle<br />AU_G: Geelong<br />AU_L: Launceston<br />AU_M: Melbourne<br />AU_N: Newcastle<br />AU_R: Goulburn<br />AU_S: Sydney<br />PS: Private Sales<br />T: Auctions Plus Sales'
    SoftwareCompany:
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
      type: integer
      description: '1: Talman<br />2: Symbotic<br />3: Jumbuck/Datacon<br />4: Jemalong<br />5: NA - no value<br />6: Modiano<br />7: AWH<br />6: AWTA'
      format: int32
    SoftwareIdentifier:
      type: object
      properties:
        softwareCompany:
          $ref: '#/components/schemas/SoftwareCompany'
        version:
          pattern: '-?\d{1,4}'
          type: integer
          description: Version no. e.g. 2400
          format: int32
          nullable: true
        programName:
          maxLength: 4
          minLength: 0
          type: string
          nullable: true
      additionalProperties: false
    TransmissionHeader:
      required:
        - abn
        - countryOfOrigin
        - currentReceiver
        - dateFormatLastRevised
        - dateTransmissionFileCreated
        - documentOriginator
      type: object
      properties:
        dateFormatLastRevised:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD)
          format: date
        dateTransmissionFileCreated:
          maxLength: 10
          minLength: 0
          pattern: /(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$/
          type: string
          description: Date value in ISO standard UTC date format. e.g. 2024-03-21 (YYYY-MM-DD)
          format: date
        countryOfOrigin:
          $ref: '#/components/schemas/CountryCode'
        documentOriginator:
          $ref: '#/components/schemas/Organisation'
        currentReceiver:
          $ref: '#/components/schemas/Organisation'
        versionNumber:
          pattern: '-?\d{1,2}'
          type: integer
          description: Two digits. e.g. 99
          format: int32
          nullable: true
        softwareIdentifier:
          $ref: '#/components/schemas/SoftwareIdentifier'
        abn:
          maxLength: 11
          minLength: 0
          pattern: ^[0-9]+$
          type: string
          description: Australian Business Number, 11 digits string
      additionalProperties: false
    WeightNote:
      required:
        - prefix
        - suffix
      type: object
      properties:
        prefix:
          maxLength: 1
          minLength: 0
          type: string
        suffix:
          maxLength: 7
          minLength: 0
          pattern: '-?\d{1,7}'
          type: string
      additionalProperties: false
    WoolTypeGroup:
      enum:
        - MFLC
        - MSKT
        - XBFS
        - ODDS
      type: string
      description: 'A code to indicate which section of the sale that lot belongs.<br />MFLC: Merino fleece types<br />MSKT: Merino fleece types<br />XBFS: Merino fleece types<br />ODDS: Merino fleece types'
    WoolinkSaleSystem:
      enum:
        - A
        - H
        - O
        - W
        - S
        - T
        - E
      type: string
      description: 'A: Auction<br />H: Holding<br />O: Offer board<br />W: Wool International<br />S: Spot Sale<br />T: Tender<br />E:Electronic Auction'
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Access Token that is added in the Authorization header of the HTTP request. Example: "Authorization: Bearer {token}". The JWT serves as a credential that proves the identity of the client to the server.'
      name: Authorization
      in: header
    oauth2:
      type: oauth2
      description: Authentication for client applications by providing Client ID and Client Secret for an JWT Access Token.
      flows:
        clientCredentials:
          tokenUrl: /auth-server/oauth/token
          scopes: {}
security:
  - Bearer: []
